import { BirthdayPickerSheet } from '@features/profile';
import { CityPickerSheet } from '@features/search-filters';
import { BadgeText, Button, CountedTabs, FullPageModal } from '@ui';
import { normalizePhone } from '../model/profileStorage';
import type { ProfileController } from '../model/useProfileController';
import { ProfileContactDialog } from './ProfileContactDialog';
import { ProfileDeleteDialogs } from './ProfileDeleteDialogs';
import { ProfileSessionDialogs } from './ProfileSessionDialogs';
import { ProfileSettingsPanels } from './ProfileSettingsPanels';

export function ProfileSettingsFlow({ controller }: { controller: ProfileController }) {
  const { draft, settingsOpen, birthdayPickerOpen, setBirthdayPickerOpen, cityPickerOpen, setCityPickerOpen, settingsTab, settingsSwipeOffset, settingsSwipeDragging, settingsTabsHidden, sessions, dialog, visibleDialog, renderedSessionDialog, dialogValue, setDialogValue, contactTarget, verificationChannel, verificationIdentifier, verificationSeconds, sessionDialog, setSessionDialog, signOutOpen, setSignOutOpen, sessionTarget, error, setError, avatarError, setAvatarError, desktopProfile, settingsPanelNodesRef, completion, contactDialogOpen, closeSettings, handleSettingsScroll, changeSettingsTab, startSettingsSwipe, moveSettingsSwipe, finishSettingsSwipe, cancelSettingsSwipe, saveProfile, openContactDialog, beginAccountVerification, confirmAccountVerification, confirmNewContact, closeContactDialog, beginNewContactVerification, resendVerificationCode, useEmailVerificationFallback, requestRevokeSession, requestRevokeOtherSessions, confirmSessionRevoke, deleteAccount, openDeleteDialog, discardDraft, patchDraft, clearNameError, applyBirthday, selectCity, signOut } = controller;

  return (
    <>
      <FullPageModal open={settingsOpen && (!desktopProfile || (!dialog && !birthdayPickerOpen && !cityPickerOpen))} onClose={closeSettings} title="Настройки профиля" closeLabel="Закрыть настройки" layerClassName="profile-settings-layer" className="profile-settings-shell" headerClassName="profile-settings-header" headerEnd={<BadgeText>{completion}%</BadgeText>} headerAfter={<CountedTabs mode="settings" standardTypography animatedIndicator className={`profile-settings-tabs ${settingsTabsHidden ? 'is-hidden' : ''}`} value={settingsTab} ariaLabel="Раздел настроек" items={[{ value: 'basic', label: 'Основное', panelId: 'profile-settings-basic-panel' }, { value: 'security', label: 'Безопасность', panelId: 'profile-settings-security-panel' }]} onChange={changeSettingsTab} />} footerClassName="profile-settings-footer dialog-action-footer" footer={<><Button size="md" mode="outline" tone="neutral" stretched onClick={discardDraft}>Позже</Button><Button size="md" mode="solid" tone="primary" stretched onClick={saveProfile}>Сохранить</Button></>} exitDuration={420}>
        <ProfileSettingsPanels activeTab={settingsTab} swipeDragging={settingsSwipeDragging} swipeOffset={settingsSwipeOffset} draft={draft} sessions={sessions} avatarError={avatarError} nameError={error === 'Введите имя — минимум 2 символа.' ? error : undefined} onTouchStart={startSettingsSwipe} onTouchMove={moveSettingsSwipe} onTouchEnd={finishSettingsSwipe} onTouchCancel={cancelSettingsSwipe} onPanelNode={(tab, node) => { settingsPanelNodesRef.current[tab] = node; }} onPanelScroll={handleSettingsScroll} onDraftPatch={patchDraft} onAvatarError={setAvatarError} onClearNameError={clearNameError} onOpenContact={openContactDialog} onOpenCity={() => setCityPickerOpen(true)} onOpenBirthday={() => setBirthdayPickerOpen(true)} onRequestRevokeSession={requestRevokeSession} onRequestRevokeOtherSessions={requestRevokeOtherSessions} onOpenDelete={openDeleteDialog} />
      </FullPageModal>

      <ProfileSessionDialogs sessionDialog={sessionDialog} renderedSessionDialog={renderedSessionDialog} sessionTargetLabel={sessionTarget.label} signOutOpen={signOutOpen} onCloseSessionDialog={() => setSessionDialog(null)} onConfirmSessionRevoke={confirmSessionRevoke} onCloseSignOut={() => setSignOutOpen(false)} onSignOut={signOut} />
      <BirthdayPickerSheet open={birthdayPickerOpen} value={draft.birthday} desktopModal onClose={() => setBirthdayPickerOpen(false)} onApply={applyBirthday} />
      <CityPickerSheet open={cityPickerOpen} value={draft.city || null} allowAny={false} autoFocus={false} onClose={() => setCityPickerOpen(false)} onSelect={selectCity} />
      <ProfileContactDialog open={contactDialogOpen} visibleDialog={visibleDialog} contactTarget={contactTarget} verificationChannel={verificationChannel} verificationIdentifier={verificationIdentifier} verificationSeconds={verificationSeconds} dialogValue={dialogValue} error={error} hasFallbackEmail={Boolean(draft.email.trim())} onClose={closeContactDialog} onBeginAccountVerification={beginAccountVerification} onConfirmAccountVerification={confirmAccountVerification} onConfirmNewContact={confirmNewContact} onResetValue={() => { setDialogValue(contactTarget === 'phone' && visibleDialog === 'contact-input' ? '+7 ' : ''); setError(''); }} onBeginNewContactVerification={beginNewContactVerification} onValueChange={setDialogValue} onPhoneDigitsChange={(value) => { const localDigits = value.replace(/\D/g, '').replace(/^[78]/, ''); setDialogValue(normalizePhone(`+7 ${localDigits}`)); }} onClearError={() => setError('')} onResendVerificationCode={resendVerificationCode} onUseEmailFallback={useEmailVerificationFallback} />
      <ProfileDeleteDialogs dialog={dialog} confirmationValue={dialogValue} onClose={closeContactDialog} onConfirmationValueChange={setDialogValue} onDelete={deleteAccount} />
    </>
  );
}
