// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_token (user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, now())
`

type CreateRefreshTokenParams struct {
	UserID    int32
	TokenHash string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, roles, deleted, is_verified, enable, created_at, updated_at)
VALUES ($1, $2, false, true, true, now(), now())
RETURNING id, name, surname, email, phone, city, avatar_url, is_verified, roles, birthday
`

type CreateUserParams struct {
	Email string
	Roles []byte
}

type CreateUserRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Roles)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
	)
	return i, err
}

const deleteEmailLoginCode = `-- name: DeleteEmailLoginCode :exec
DELETE FROM email_login_code WHERE email = $1
`

func (q *Queries) DeleteEmailLoginCode(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteEmailLoginCode, email)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getEmailLoginCode = `-- name: GetEmailLoginCode :one
SELECT email, code_hash, expires_at, attempts, created_at
FROM email_login_code
WHERE email = $1
`

func (q *Queries) GetEmailLoginCode(ctx context.Context, email string) (EmailLoginCode, error) {
	row := q.db.QueryRow(ctx, getEmailLoginCode, email)
	var i EmailLoginCode
	err := row.Scan(
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at
FROM refresh_token
WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, surname, email, phone, city, avatar_url, is_verified, roles, birthday
FROM "user"
WHERE email = $1 AND deleted = false
`

type GetUserByEmailRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, surname, email, phone, city, avatar_url, is_verified, roles, birthday
FROM "user"
WHERE id = $1 AND deleted = false
`

type GetUserByIDRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
	)
	return i, err
}

const incrementEmailLoginCodeAttempts = `-- name: IncrementEmailLoginCodeAttempts :exec
UPDATE email_login_code SET attempts = attempts + 1 WHERE email = $1
`

func (q *Queries) IncrementEmailLoginCodeAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, incrementEmailLoginCodeAttempts, email)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_token SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE "user"
SET email = $2,
    updated_at = now()
WHERE id = $1 AND deleted = false
RETURNING id, name, surname, email, phone, city, avatar_url, is_verified, roles, birthday
`

type UpdateUserEmailParams struct {
	ID    int32
	Email string
}

type UpdateUserEmailRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE "user"
SET name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    city = COALESCE($3, city),
    birthday = COALESCE($4, birthday),
    avatar_url = COALESCE($5, avatar_url),
    updated_at = now()
WHERE id = $6 AND deleted = false
RETURNING id, name, surname, email, phone, city, avatar_url, is_verified, roles, birthday
`

type UpdateUserProfileParams struct {
	Name      *string
	Phone     *string
	City      *string
	Birthday  pgtype.Date
	AvatarUrl *string
	ID        int32
}

type UpdateUserProfileRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Name,
		arg.Phone,
		arg.City,
		arg.Birthday,
		arg.AvatarUrl,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
	)
	return i, err
}

const upsertEmailLoginCode = `-- name: UpsertEmailLoginCode :exec
INSERT INTO email_login_code (email, code_hash, expires_at, attempts, created_at)
VALUES ($1, $2, $3, 0, now())
ON CONFLICT (email) DO UPDATE
SET code_hash = EXCLUDED.code_hash,
    expires_at = EXCLUDED.expires_at,
    attempts = 0,
    created_at = now()
`

type UpsertEmailLoginCodeParams struct {
	Email     string
	CodeHash  string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) UpsertEmailLoginCode(ctx context.Context, arg UpsertEmailLoginCodeParams) error {
	_, err := q.db.Exec(ctx, upsertEmailLoginCode, arg.Email, arg.CodeHash, arg.ExpiresAt)
	return err
}
