// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeUser = `-- name: AnonymizeUser :exec
UPDATE "user" SET
    email = 'deleted_' || id || '@deleted.sutki.ru',
    name = 'Удаленный пользователь',
    surname = '',
    patronymic = '',
    password = NULL,
    google_id = NULL,
    vk_id = NULL,
    phone = '',
    avatar_url = '',
    birthday = NULL,
    deleted = true,
    enable = false,
    code = NULL,
    date_code = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) AnonymizeUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, anonymizeUser, id)
	return err
}

const checkUserActiveBookings = `-- name: CheckUserActiveBookings :one
SELECT count(*)::bigint
FROM request r
JOIN house h ON h.id = r.house_id
WHERE (r.user_id = $1 OR h.owner_id = $1)
  AND (
    r.status = 'in_progress'
    OR (r.status = 'confirmed' AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE))
  )
`

func (q *Queries) CheckUserActiveBookings(ctx context.Context, userID *int32) (int64, error) {
	row := q.db.QueryRow(ctx, checkUserActiveBookings, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPersonalDataRevocation = `-- name: CreatePersonalDataRevocation :exec
INSERT INTO personal_data_revocation (user_id, email_hash, revoked_at)
VALUES ($1, $2, now())
`

type CreatePersonalDataRevocationParams struct {
	UserID    int32
	EmailHash string
}

func (q *Queries) CreatePersonalDataRevocation(ctx context.Context, arg CreatePersonalDataRevocationParams) error {
	_, err := q.db.Exec(ctx, createPersonalDataRevocation, arg.UserID, arg.EmailHash)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_token (user_id, token_hash, expires_at, device_name, device_os, app_version, ip_address, location, last_active_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())
RETURNING id
`

type CreateRefreshTokenParams struct {
	UserID     int32
	TokenHash  string
	ExpiresAt  pgtype.Timestamp
	DeviceName *string
	DeviceOs   *string
	AppVersion *string
	IpAddress  *string
	Location   *string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.DeviceName,
		arg.DeviceOs,
		arg.AppVersion,
		arg.IpAddress,
		arg.Location,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, roles, deleted, is_verified, enable, created_at, updated_at)
VALUES ($1, $2, false, true, true, now(), now())
RETURNING id, name, surname, patronymic, email, phone, city, avatar_url, is_verified, roles, birthday, vk_id
`

type CreateUserParams struct {
	Email string
	Roles []byte
}

type CreateUserRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Patronymic *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
	VkID       *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Roles)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
	)
	return i, err
}

const deleteEmailLoginCode = `-- name: DeleteEmailLoginCode :exec
DELETE FROM email_login_code WHERE email = $1
`

func (q *Queries) DeleteEmailLoginCode(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteEmailLoginCode, email)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserDeviceTokens = `-- name: DeleteUserDeviceTokens :exec
DELETE FROM device_token WHERE user_id = $1
`

func (q *Queries) DeleteUserDeviceTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserDeviceTokens, userID)
	return err
}

const deleteUserFavorites = `-- name: DeleteUserFavorites :exec
DELETE FROM favorite WHERE user_id = $1
`

func (q *Queries) DeleteUserFavorites(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserFavorites, userID)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM refresh_token WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokens, userID)
	return err
}

const getEmailLoginCode = `-- name: GetEmailLoginCode :one
SELECT email, code_hash, expires_at, attempts, created_at
FROM email_login_code
WHERE email = $1
`

func (q *Queries) GetEmailLoginCode(ctx context.Context, email string) (EmailLoginCode, error) {
	row := q.db.QueryRow(ctx, getEmailLoginCode, email)
	var i EmailLoginCode
	err := row.Scan(
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at, device_name, device_os, app_version, ip_address, location, last_active_at
FROM refresh_token
WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.DeviceName,
		&i.DeviceOs,
		&i.AppVersion,
		&i.IpAddress,
		&i.Location,
		&i.LastActiveAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at, device_name, device_os, app_version, ip_address, location, last_active_at
FROM refresh_token
WHERE id = $1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id int64) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.DeviceName,
		&i.DeviceOs,
		&i.AppVersion,
		&i.IpAddress,
		&i.Location,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, surname, patronymic, email, phone, city, avatar_url, is_verified, roles, birthday, vk_id
FROM "user"
WHERE email = $1 AND deleted = false
`

type GetUserByEmailRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Patronymic *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
	VkID       *string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
  u.id, u.name, u.surname, u.patronymic, u.email, u.phone, u.city, u.avatar_url, u.is_verified, u.roles, u.birthday, u.vk_id,
  (
    SELECT count(*)::int
    FROM house h
    WHERE h.owner_id = u.id AND h.deleted = false
  ) AS listings_count,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    JOIN house h ON h.id = rv.house_id
    WHERE h.owner_id = u.id AND rv.status = 'active'
  ), 0.0)::float8 AS rating
FROM "user" u
WHERE u.id = $1 AND u.deleted = false
`

type GetUserByIDRow struct {
	ID            int32
	Name          *string
	Surname       *string
	Patronymic    *string
	Email         string
	Phone         *string
	City          *string
	AvatarUrl     *string
	IsVerified    bool
	Roles         []byte
	Birthday      pgtype.Date
	VkID          *string
	ListingsCount int32
	Rating        float64
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
		&i.ListingsCount,
		&i.Rating,
	)
	return i, err
}

const incrementEmailLoginCodeAttempts = `-- name: IncrementEmailLoginCodeAttempts :exec
UPDATE email_login_code SET attempts = attempts + 1 WHERE email = $1
`

func (q *Queries) IncrementEmailLoginCodeAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, incrementEmailLoginCodeAttempts, email)
	return err
}

const listActiveRefreshTokens = `-- name: ListActiveRefreshTokens :many
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at, device_name, device_os, app_version, ip_address, location, last_active_at
FROM refresh_token
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_active_at DESC
`

func (q *Queries) ListActiveRefreshTokens(ctx context.Context, userID int32) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveRefreshTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.DeviceName,
			&i.DeviceOs,
			&i.AppVersion,
			&i.IpAddress,
			&i.Location,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllOtherRefreshTokens = `-- name: RevokeAllOtherRefreshTokens :exec
UPDATE refresh_token SET revoked_at = now()
WHERE user_id = $1 AND id != $2 AND revoked_at IS NULL
`

type RevokeAllOtherRefreshTokensParams struct {
	UserID int32
	ID     int64
}

func (q *Queries) RevokeAllOtherRefreshTokens(ctx context.Context, arg RevokeAllOtherRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAllOtherRefreshTokens, arg.UserID, arg.ID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_token SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :exec
UPDATE refresh_token SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenByIDParams struct {
	ID     int64
	UserID int32
}

func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, arg RevokeRefreshTokenByIDParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByID, arg.ID, arg.UserID)
	return err
}

const softDeleteUserHouses = `-- name: SoftDeleteUserHouses :exec
UPDATE house SET deleted = true, updated_at = now() WHERE owner_id = $1
`

func (q *Queries) SoftDeleteUserHouses(ctx context.Context, ownerID int32) error {
	_, err := q.db.Exec(ctx, softDeleteUserHouses, ownerID)
	return err
}

const updateRefreshTokenActiveTime = `-- name: UpdateRefreshTokenActiveTime :exec
UPDATE refresh_token SET last_active_at = $2
WHERE id = $1
`

type UpdateRefreshTokenActiveTimeParams struct {
	ID           int64
	LastActiveAt pgtype.Timestamp
}

func (q *Queries) UpdateRefreshTokenActiveTime(ctx context.Context, arg UpdateRefreshTokenActiveTimeParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenActiveTime, arg.ID, arg.LastActiveAt)
	return err
}

const updateRefreshTokenLocation = `-- name: UpdateRefreshTokenLocation :exec
UPDATE refresh_token SET location = $2
WHERE id = $1
`

type UpdateRefreshTokenLocationParams struct {
	ID       int64
	Location *string
}

func (q *Queries) UpdateRefreshTokenLocation(ctx context.Context, arg UpdateRefreshTokenLocationParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenLocation, arg.ID, arg.Location)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE "user"
SET email = $2,
    updated_at = now()
WHERE id = $1 AND deleted = false
RETURNING id, name, surname, patronymic, email, phone, city, avatar_url, is_verified, roles, birthday, vk_id
`

type UpdateUserEmailParams struct {
	ID    int32
	Email string
}

type UpdateUserEmailRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Patronymic *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
	VkID       *string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE "user"
SET name = COALESCE($1, name),
    surname = CASE WHEN $2::text = '' THEN NULL ELSE COALESCE($2::text, surname) END,
    patronymic = CASE WHEN $3::text = '' THEN NULL ELSE COALESCE($3::text, patronymic) END,
    phone = COALESCE($4, phone),
    city = COALESCE($5, city),
    birthday = COALESCE($6, birthday),
    avatar_url = COALESCE($7, avatar_url),
    vk_id = CASE WHEN $8::boolean = true THEN NULL ELSE COALESCE($9, vk_id) END,
    updated_at = now()
WHERE id = $10 AND deleted = false
RETURNING id, name, surname, patronymic, email, phone, city, avatar_url, is_verified, roles, birthday, vk_id
`

type UpdateUserProfileParams struct {
	Name       *string
	Surname    *string
	Patronymic *string
	Phone      *string
	City       *string
	Birthday   pgtype.Date
	AvatarUrl  *string
	VkIDDoNull *bool
	VkID       *string
	ID         int32
}

type UpdateUserProfileRow struct {
	ID         int32
	Name       *string
	Surname    *string
	Patronymic *string
	Email      string
	Phone      *string
	City       *string
	AvatarUrl  *string
	IsVerified bool
	Roles      []byte
	Birthday   pgtype.Date
	VkID       *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.Phone,
		arg.City,
		arg.Birthday,
		arg.AvatarUrl,
		arg.VkIDDoNull,
		arg.VkID,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
	)
	return i, err
}

const upsertEmailLoginCode = `-- name: UpsertEmailLoginCode :exec
INSERT INTO email_login_code (email, code_hash, expires_at, attempts, created_at)
VALUES ($1, $2, $3, 0, now())
ON CONFLICT (email) DO UPDATE
SET code_hash = EXCLUDED.code_hash,
    expires_at = EXCLUDED.expires_at,
    attempts = 0,
    created_at = now()
`

type UpsertEmailLoginCodeParams struct {
	Email     string
	CodeHash  string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) UpsertEmailLoginCode(ctx context.Context, arg UpsertEmailLoginCodeParams) error {
	_, err := q.db.Exec(ctx, upsertEmailLoginCode, arg.Email, arg.CodeHash, arg.ExpiresAt)
	return err
}
