// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeUser = `-- name: AnonymizeUser :exec
UPDATE "user" SET
    email = 'deleted_' || id || '@deleted.sutki.ru',
    name = 'Удаленный пользователь',
    surname = '',
    patronymic = '',
    password = NULL,
    google_id = NULL,
    vk_id = NULL,
    phone = '',
    phone_normalized = NULL,
    phone_verified_at = NULL,
    avatar_url = '',
    birthday = NULL,
    deleted = true,
    enable = false,
    code = NULL,
    date_code = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) AnonymizeUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, anonymizeUser, id)
	return err
}

const checkUserActiveBookings = `-- name: CheckUserActiveBookings :one
SELECT count(*)::bigint
FROM request r
JOIN house h ON h.id = r.house_id
WHERE (r.user_id = $1 OR h.owner_id = $1)
  AND (
    r.status IN ('in_progress', 'pending')
    OR (r.status = 'confirmed' AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE))
  )
`

func (q *Queries) CheckUserActiveBookings(ctx context.Context, userID *int32) (int64, error) {
	row := q.db.QueryRow(ctx, checkUserActiveBookings, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPersonalDataRevocation = `-- name: CreatePersonalDataRevocation :exec
INSERT INTO personal_data_revocation (user_id, email_hash, revoked_at)
VALUES ($1, $2, now())
`

type CreatePersonalDataRevocationParams struct {
	UserID    int32
	EmailHash string
}

func (q *Queries) CreatePersonalDataRevocation(ctx context.Context, arg CreatePersonalDataRevocationParams) error {
	_, err := q.db.Exec(ctx, createPersonalDataRevocation, arg.UserID, arg.EmailHash)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_token (user_id, token_hash, expires_at, device_name, device_os, app_version, ip_address, location, last_active_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())
RETURNING id
`

type CreateRefreshTokenParams struct {
	UserID     int32
	TokenHash  string
	ExpiresAt  pgtype.Timestamp
	DeviceName *string
	DeviceOs   *string
	AppVersion *string
	IpAddress  *string
	Location   *string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.DeviceName,
		arg.DeviceOs,
		arg.AppVersion,
		arg.IpAddress,
		arg.Location,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (email, phone, phone_normalized, phone_verified_at, roles, deleted, is_verified, enable, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, false, true, true, now(), now())
RETURNING id, name, surname, patronymic, email, phone, phone_normalized, phone_verified_at, city, avatar_url, is_verified, roles, birthday, vk_id, created_at
`

type CreateUserParams struct {
	Email           *string
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	Roles           []byte
}

type CreateUserRow struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           *string
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	City            *string
	AvatarUrl       *string
	IsVerified      bool
	Roles           []byte
	Birthday        pgtype.Date
	VkID            *string
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.PhoneNormalized,
		arg.PhoneVerifiedAt,
		arg.Roles,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.PhoneNormalized,
		&i.PhoneVerifiedAt,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthCode = `-- name: DeleteAuthCode :exec
DELETE FROM auth_code WHERE channel = $1 AND target = $2
`

type DeleteAuthCodeParams struct {
	Channel string
	Target  string
}

func (q *Queries) DeleteAuthCode(ctx context.Context, arg DeleteAuthCodeParams) error {
	_, err := q.db.Exec(ctx, deleteAuthCode, arg.Channel, arg.Target)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserDeviceTokens = `-- name: DeleteUserDeviceTokens :exec
DELETE FROM device_token WHERE user_id = $1
`

func (q *Queries) DeleteUserDeviceTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserDeviceTokens, userID)
	return err
}

const deleteUserFavorites = `-- name: DeleteUserFavorites :exec
DELETE FROM favorite WHERE user_id = $1
`

func (q *Queries) DeleteUserFavorites(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserFavorites, userID)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM refresh_token WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokens, userID)
	return err
}

const getAuthCode = `-- name: GetAuthCode :one
SELECT channel, target, code_hash, expires_at, attempts, created_at, delivery_provider, delivery_id, delivery_cost
FROM auth_code
WHERE channel = $1 AND target = $2
`

type GetAuthCodeParams struct {
	Channel string
	Target  string
}

func (q *Queries) GetAuthCode(ctx context.Context, arg GetAuthCodeParams) (AuthCode, error) {
	row := q.db.QueryRow(ctx, getAuthCode, arg.Channel, arg.Target)
	var i AuthCode
	err := row.Scan(
		&i.Channel,
		&i.Target,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
		&i.DeliveryProvider,
		&i.DeliveryID,
		&i.DeliveryCost,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at, device_name, device_os, app_version, ip_address, location, last_active_at
FROM refresh_token
WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.DeviceName,
		&i.DeviceOs,
		&i.AppVersion,
		&i.IpAddress,
		&i.Location,
		&i.LastActiveAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at, device_name, device_os, app_version, ip_address, location, last_active_at
FROM refresh_token
WHERE id = $1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id int64) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.DeviceName,
		&i.DeviceOs,
		&i.AppVersion,
		&i.IpAddress,
		&i.Location,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, surname, patronymic, email, phone, phone_normalized, phone_verified_at, city, avatar_url, is_verified, roles, birthday, vk_id, created_at
FROM "user"
WHERE email = $1 AND deleted = false
`

type GetUserByEmailRow struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           *string
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	City            *string
	AvatarUrl       *string
	IsVerified      bool
	Roles           []byte
	Birthday        pgtype.Date
	VkID            *string
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.PhoneNormalized,
		&i.PhoneVerifiedAt,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
  u.id, u.name, u.surname, u.patronymic, u.email, u.phone, u.phone_normalized, u.phone_verified_at, u.city, u.avatar_url, u.is_verified, u.roles, u.birthday, u.vk_id, u.created_at,
  (
    SELECT count(*)::int
    FROM house h
    WHERE h.owner_id = u.id AND h.deleted = false
  ) AS listings_count,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    JOIN house h ON h.id = rv.house_id
    WHERE h.owner_id = u.id AND rv.status = 'active'
  ), 0.0)::float8 AS rating
FROM "user" u
WHERE u.id = $1 AND u.deleted = false
`

type GetUserByIDRow struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           *string
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	City            *string
	AvatarUrl       *string
	IsVerified      bool
	Roles           []byte
	Birthday        pgtype.Date
	VkID            *string
	CreatedAt       pgtype.Timestamp
	ListingsCount   int32
	Rating          float64
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.PhoneNormalized,
		&i.PhoneVerifiedAt,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
		&i.CreatedAt,
		&i.ListingsCount,
		&i.Rating,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, name, surname, patronymic, email, phone, phone_normalized, phone_verified_at, city, avatar_url, is_verified, roles, birthday, vk_id, created_at
FROM "user"
WHERE phone_normalized = $1 AND deleted = false
`

type GetUserByPhoneRow struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           *string
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	City            *string
	AvatarUrl       *string
	IsVerified      bool
	Roles           []byte
	Birthday        pgtype.Date
	VkID            *string
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNormalized *string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNormalized)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.PhoneNormalized,
		&i.PhoneVerifiedAt,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAuthCodeAttempts = `-- name: IncrementAuthCodeAttempts :exec
UPDATE auth_code SET attempts = attempts + 1 WHERE channel = $1 AND target = $2
`

type IncrementAuthCodeAttemptsParams struct {
	Channel string
	Target  string
}

func (q *Queries) IncrementAuthCodeAttempts(ctx context.Context, arg IncrementAuthCodeAttemptsParams) error {
	_, err := q.db.Exec(ctx, incrementAuthCodeAttempts, arg.Channel, arg.Target)
	return err
}

const listActiveRefreshTokens = `-- name: ListActiveRefreshTokens :many
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at, device_name, device_os, app_version, ip_address, location, last_active_at
FROM refresh_token
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_active_at DESC
`

func (q *Queries) ListActiveRefreshTokens(ctx context.Context, userID int32) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveRefreshTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.DeviceName,
			&i.DeviceOs,
			&i.AppVersion,
			&i.IpAddress,
			&i.Location,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllOtherRefreshTokens = `-- name: RevokeAllOtherRefreshTokens :exec
UPDATE refresh_token SET revoked_at = now()
WHERE user_id = $1 AND id != $2 AND revoked_at IS NULL
`

type RevokeAllOtherRefreshTokensParams struct {
	UserID int32
	ID     int64
}

func (q *Queries) RevokeAllOtherRefreshTokens(ctx context.Context, arg RevokeAllOtherRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAllOtherRefreshTokens, arg.UserID, arg.ID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_token SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :exec
UPDATE refresh_token SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenByIDParams struct {
	ID     int64
	UserID int32
}

func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, arg RevokeRefreshTokenByIDParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByID, arg.ID, arg.UserID)
	return err
}

const softDeleteUserHouses = `-- name: SoftDeleteUserHouses :exec
UPDATE house SET deleted = true, updated_at = now() WHERE owner_id = $1
`

func (q *Queries) SoftDeleteUserHouses(ctx context.Context, ownerID int32) error {
	_, err := q.db.Exec(ctx, softDeleteUserHouses, ownerID)
	return err
}

const updateRefreshTokenActiveTime = `-- name: UpdateRefreshTokenActiveTime :exec
UPDATE refresh_token SET last_active_at = $2
WHERE id = $1
`

type UpdateRefreshTokenActiveTimeParams struct {
	ID           int64
	LastActiveAt pgtype.Timestamp
}

func (q *Queries) UpdateRefreshTokenActiveTime(ctx context.Context, arg UpdateRefreshTokenActiveTimeParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenActiveTime, arg.ID, arg.LastActiveAt)
	return err
}

const updateRefreshTokenLocation = `-- name: UpdateRefreshTokenLocation :exec
UPDATE refresh_token SET location = $2
WHERE id = $1
`

type UpdateRefreshTokenLocationParams struct {
	ID       int64
	Location *string
}

func (q *Queries) UpdateRefreshTokenLocation(ctx context.Context, arg UpdateRefreshTokenLocationParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenLocation, arg.ID, arg.Location)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE "user"
SET email = $2,
    updated_at = now()
WHERE id = $1 AND deleted = false
RETURNING id, name, surname, patronymic, email, phone, phone_normalized, phone_verified_at, city, avatar_url, is_verified, roles, birthday, vk_id
`

type UpdateUserEmailParams struct {
	ID    int32
	Email *string
}

type UpdateUserEmailRow struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           *string
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	City            *string
	AvatarUrl       *string
	IsVerified      bool
	Roles           []byte
	Birthday        pgtype.Date
	VkID            *string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.PhoneNormalized,
		&i.PhoneVerifiedAt,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
	)
	return i, err
}

const updateUserPhone = `-- name: UpdateUserPhone :one
UPDATE "user"
SET phone = $2,
    phone_normalized = $3,
    phone_verified_at = $4,
    updated_at = now()
WHERE id = $1 AND deleted = false
RETURNING id, name, surname, patronymic, email, phone, phone_normalized, phone_verified_at, city, avatar_url, is_verified, roles, birthday, vk_id, created_at
`

type UpdateUserPhoneParams struct {
	ID              int32
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
}

type UpdateUserPhoneRow struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           *string
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	City            *string
	AvatarUrl       *string
	IsVerified      bool
	Roles           []byte
	Birthday        pgtype.Date
	VkID            *string
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (UpdateUserPhoneRow, error) {
	row := q.db.QueryRow(ctx, updateUserPhone,
		arg.ID,
		arg.Phone,
		arg.PhoneNormalized,
		arg.PhoneVerifiedAt,
	)
	var i UpdateUserPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.PhoneNormalized,
		&i.PhoneVerifiedAt,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE "user"
SET name = COALESCE($1, name),
    surname = CASE WHEN $2::text = '' THEN NULL ELSE COALESCE($2::text, surname) END,
    patronymic = CASE WHEN $3::text = '' THEN NULL ELSE COALESCE($3::text, patronymic) END,
    phone = COALESCE($4, phone),
    city = COALESCE($5, city),
    birthday = COALESCE($6, birthday),
    avatar_url = COALESCE($7, avatar_url),
    vk_id = CASE WHEN $8::boolean = true THEN NULL ELSE COALESCE($9, vk_id) END,
    phone_normalized = COALESCE($10, phone_normalized),
    phone_verified_at = COALESCE($11, phone_verified_at),
    updated_at = now()
WHERE id = $12 AND deleted = false
RETURNING id, name, surname, patronymic, email, phone, phone_normalized, phone_verified_at, city, avatar_url, is_verified, roles, birthday, vk_id, created_at
`

type UpdateUserProfileParams struct {
	Name            *string
	Surname         *string
	Patronymic      *string
	Phone           *string
	City            *string
	Birthday        pgtype.Date
	AvatarUrl       *string
	VkIDDoNull      *bool
	VkID            *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	ID              int32
}

type UpdateUserProfileRow struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           *string
	Phone           *string
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	City            *string
	AvatarUrl       *string
	IsVerified      bool
	Roles           []byte
	Birthday        pgtype.Date
	VkID            *string
	CreatedAt       pgtype.Timestamp
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.Phone,
		arg.City,
		arg.Birthday,
		arg.AvatarUrl,
		arg.VkIDDoNull,
		arg.VkID,
		arg.PhoneNormalized,
		arg.PhoneVerifiedAt,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Email,
		&i.Phone,
		&i.PhoneNormalized,
		&i.PhoneVerifiedAt,
		&i.City,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.Roles,
		&i.Birthday,
		&i.VkID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAuthCode = `-- name: UpsertAuthCode :exec
INSERT INTO auth_code (
  channel, target, code_hash, expires_at, attempts, created_at, delivery_provider, delivery_id, delivery_cost
)
VALUES ($1, $2, $3, $4, 0, now(), $5, $6, $7)
ON CONFLICT (channel, target) DO UPDATE
SET code_hash = EXCLUDED.code_hash,
    expires_at = EXCLUDED.expires_at,
    attempts = 0,
    created_at = now(),
    delivery_provider = EXCLUDED.delivery_provider,
    delivery_id = EXCLUDED.delivery_id,
    delivery_cost = EXCLUDED.delivery_cost
`

type UpsertAuthCodeParams struct {
	Channel          string
	Target           string
	CodeHash         string
	ExpiresAt        pgtype.Timestamptz
	DeliveryProvider *string
	DeliveryID       *string
	DeliveryCost     *string
}

func (q *Queries) UpsertAuthCode(ctx context.Context, arg UpsertAuthCodeParams) error {
	_, err := q.db.Exec(ctx, upsertAuthCode,
		arg.Channel,
		arg.Target,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.DeliveryProvider,
		arg.DeliveryID,
		arg.DeliveryCost,
	)
	return err
}
