// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationParticipant = `-- name: AddConversationParticipant :exec
INSERT INTO conversation_participant (conversation_id, user_id, last_read_at, last_read_message_id)
VALUES ($1, $2, now(), 0)
`

type AddConversationParticipantParams struct {
	ConversationID int64
	UserID         int32
}

func (q *Queries) AddConversationParticipant(ctx context.Context, arg AddConversationParticipantParams) error {
	_, err := q.db.Exec(ctx, addConversationParticipant, arg.ConversationID, arg.UserID)
	return err
}

const checkParticipantExists = `-- name: CheckParticipantExists :one
SELECT EXISTS(
    SELECT 1 FROM conversation_participant 
    WHERE conversation_id = $1 AND user_id = $2
)::boolean
`

type CheckParticipantExistsParams struct {
	ConversationID int64
	UserID         int32
}

func (q *Queries) CheckParticipantExists(ctx context.Context, arg CheckParticipantExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkParticipantExists, arg.ConversationID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO message_attachment (message_id, url, file_name, mime_type, size_bytes, width, height)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, message_id, url, file_name, mime_type, size_bytes, width, height
`

type CreateAttachmentParams struct {
	MessageID int64
	Url       string
	FileName  *string
	MimeType  *string
	SizeBytes *int64
	Width     *int32
	Height    *int32
}

type CreateAttachmentRow struct {
	ID        int64
	MessageID int64
	Url       string
	FileName  *string
	MimeType  *string
	SizeBytes *int64
	Width     *int32
	Height    *int32
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.MessageID,
		arg.Url,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
	)
	var i CreateAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Url,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversation (house_id, created_at, updated_at)
VALUES ($1, now(), now())
RETURNING id, house_id, created_at, updated_at
`

func (q *Queries) CreateConversation(ctx context.Context, houseID *int32) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, houseID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (conversation_id, sender_id, body, created_at)
VALUES ($1, $2, $3, now())
RETURNING id, conversation_id, sender_id, body, created_at
`

type CreateMessageParams struct {
	ConversationID int64
	SenderID       *int32
	Body           *string
}

type CreateMessageRow struct {
	ID             int64
	ConversationID int64
	SenderID       *int32
	Body           *string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Body)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByParticipantsAndHouse = `-- name: GetConversationByParticipantsAndHouse :one
SELECT c.id
FROM conversation c
JOIN conversation_participant cp1 ON c.id = cp1.conversation_id
JOIN conversation_participant cp2 ON c.id = cp2.conversation_id
WHERE c.house_id = $1
  AND cp1.user_id = $2
  AND cp2.user_id = $3
  AND cp1.user_id <> cp2.user_id
LIMIT 1
`

type GetConversationByParticipantsAndHouseParams struct {
	HouseID  *int32
	UserID   int32
	UserID_2 int32
}

// 1. Поиск диалога привязанного к объекту (house_id IS NOT NULL)
func (q *Queries) GetConversationByParticipantsAndHouse(ctx context.Context, arg GetConversationByParticipantsAndHouseParams) (int64, error) {
	row := q.db.QueryRow(ctx, getConversationByParticipantsAndHouse, arg.HouseID, arg.UserID, arg.UserID_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConversationByParticipantsGeneral = `-- name: GetConversationByParticipantsGeneral :one
SELECT c.id
FROM conversation c
JOIN conversation_participant cp1 ON c.id = cp1.conversation_id
JOIN conversation_participant cp2 ON c.id = cp2.conversation_id
WHERE c.house_id IS NULL
  AND cp1.user_id = $1
  AND cp2.user_id = $2
  AND cp1.user_id <> cp2.user_id
LIMIT 1
`

type GetConversationByParticipantsGeneralParams struct {
	UserID   int32
	UserID_2 int32
}

// 2. Поиск общего диалога между пользователями (house_id IS NULL)
func (q *Queries) GetConversationByParticipantsGeneral(ctx context.Context, arg GetConversationByParticipantsGeneralParams) (int64, error) {
	row := q.db.QueryRow(ctx, getConversationByParticipantsGeneral, arg.UserID, arg.UserID_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT id, conversation_id, sender_id, body, created_at
FROM message
WHERE conversation_id = $1
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type GetConversationMessagesParams struct {
	ConversationID int64
	Column2        int64
	Limit          int32
}

type GetConversationMessagesRow struct {
	ID             int64
	ConversationID int64
	SenderID       *int32
	Body           *string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, arg.ConversationID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageAttachments = `-- name: GetMessageAttachments :many
SELECT id, message_id, url, file_name, mime_type, size_bytes, width, height
FROM message_attachment
WHERE message_id = ANY($1::bigint[])
`

type GetMessageAttachmentsRow struct {
	ID        int64
	MessageID int64
	Url       string
	FileName  *string
	MimeType  *string
	SizeBytes *int64
	Width     *int32
	Height    *int32
}

func (q *Queries) GetMessageAttachments(ctx context.Context, dollar_1 []int64) ([]GetMessageAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, getMessageAttachments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageAttachmentsRow
	for rows.Next() {
		var i GetMessageAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Url,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOtherParticipantID = `-- name: GetOtherParticipantID :one
SELECT user_id::int FROM conversation_participant
WHERE conversation_id = $1 AND user_id <> $2
LIMIT 1
`

type GetOtherParticipantIDParams struct {
	ConversationID int64
	UserID         int32
}

func (q *Queries) GetOtherParticipantID(ctx context.Context, arg GetOtherParticipantIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOtherParticipantID, arg.ConversationID, arg.UserID)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const isOtherParticipantDeleted = `-- name: IsOtherParticipantDeleted :one
SELECT COALESCE(u.deleted, false)::boolean
FROM conversation_participant cp
JOIN "user" u ON cp.user_id = u.id
WHERE cp.conversation_id = $1 AND cp.user_id <> $2
LIMIT 1
`

type IsOtherParticipantDeletedParams struct {
	ConversationID int64
	UserID         int32
}

func (q *Queries) IsOtherParticipantDeleted(ctx context.Context, arg IsOtherParticipantDeletedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOtherParticipantDeleted, arg.ConversationID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT 
    c.id AS conversation_id,
    c.house_id,
    c.updated_at AS last_activity,
    cp.last_read_message_id,
    other_cp.last_read_message_id AS other_last_read_message_id,
    (SELECT COUNT(*) FROM message m WHERE m.conversation_id = c.id AND m.id > cp.last_read_message_id) AS unread_count,
    m.id AS last_message_id,
    COALESCE(m.body, (
        SELECT CASE 
            WHEN mime_type LIKE 'image/%' THEN '[Изображение]'
            ELSE '[Документ]: ' || file_name 
        END 
        FROM message_attachment 
        WHERE message_id = m.id 
        LIMIT 1
    ), '')::text AS last_message_body,
    m.sender_id AS last_message_sender_id,
    m.created_at AS last_message_created_at,
    other_u.id AS other_user_id,
    other_u.name AS other_user_name,
    other_u.surname AS other_user_surname,
    other_u.avatar_url AS other_user_avatar_url,
    other_u.deleted AS other_user_deleted,
    h.street AS house_street,
    h.house_number AS house_number,
    h.count_room AS house_count_room,
    h.price AS house_price,
    COALESCE((
        SELECT f.path
        FROM file f
        WHERE f.house_id = h.id AND f.deleted = false
        ORDER BY f.position
        LIMIT 1
    ), '')::text AS house_cover_path
FROM conversation c
JOIN conversation_participant cp ON c.id = cp.conversation_id
JOIN conversation_participant other_cp ON c.id = other_cp.conversation_id AND other_cp.user_id <> cp.user_id
JOIN "user" other_u ON other_cp.user_id = other_u.id
LEFT JOIN house h ON c.house_id = h.id
LEFT JOIN message m ON m.conversation_id = c.id AND m.id = (
    SELECT MAX(id) FROM message WHERE conversation_id = c.id
)
WHERE cp.user_id = $1
ORDER BY c.updated_at DESC
`

type ListUserConversationsRow struct {
	ConversationID         int64
	HouseID                *int32
	LastActivity           pgtype.Timestamptz
	LastReadMessageID      *int64
	OtherLastReadMessageID *int64
	UnreadCount            int64
	LastMessageID          *int64
	LastMessageBody        string
	LastMessageSenderID    *int32
	LastMessageCreatedAt   pgtype.Timestamptz
	OtherUserID            int32
	OtherUserName          *string
	OtherUserSurname       *string
	OtherUserAvatarUrl     *string
	OtherUserDeleted       bool
	HouseStreet            *string
	HouseNumber            *string
	HouseCountRoom         *string
	HousePrice             *int32
	HouseCoverPath         string
}

// Тянет последнее сообщение с Фолбэком для медиа-вложений (превью в списке диалогов)
func (q *Queries) ListUserConversations(ctx context.Context, userID int32) ([]ListUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, listUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserConversationsRow
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.HouseID,
			&i.LastActivity,
			&i.LastReadMessageID,
			&i.OtherLastReadMessageID,
			&i.UnreadCount,
			&i.LastMessageID,
			&i.LastMessageBody,
			&i.LastMessageSenderID,
			&i.LastMessageCreatedAt,
			&i.OtherUserID,
			&i.OtherUserName,
			&i.OtherUserSurname,
			&i.OtherUserAvatarUrl,
			&i.OtherUserDeleted,
			&i.HouseStreet,
			&i.HouseNumber,
			&i.HouseCountRoom,
			&i.HousePrice,
			&i.HouseCoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationTimestamp = `-- name: UpdateConversationTimestamp :exec
UPDATE conversation
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateConversationTimestamp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateConversationTimestamp, id)
	return err
}

const updateLastReadMessage = `-- name: UpdateLastReadMessage :exec
UPDATE conversation_participant
SET last_read_message_id = $1, last_read_at = now()
WHERE conversation_id = $2 AND user_id = $3
`

type UpdateLastReadMessageParams struct {
	LastReadMessageID *int64
	ConversationID    int64
	UserID            int32
}

func (q *Queries) UpdateLastReadMessage(ctx context.Context, arg UpdateLastReadMessageParams) error {
	_, err := q.db.Exec(ctx, updateLastReadMessage, arg.LastReadMessageID, arg.ConversationID, arg.UserID)
	return err
}
