// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationParticipant = `-- name: AddConversationParticipant :exec
INSERT INTO conversation_participant (conversation_id, user_id, last_read_at, last_read_message_id)
VALUES ($1, $2, now(), 0)
`

type AddConversationParticipantParams struct {
	ConversationID int64
	UserID         int32
}

func (q *Queries) AddConversationParticipant(ctx context.Context, arg AddConversationParticipantParams) error {
	_, err := q.db.Exec(ctx, addConversationParticipant, arg.ConversationID, arg.UserID)
	return err
}

const checkChatUploadOwnership = `-- name: CheckChatUploadOwnership :one
SELECT COUNT(*) = cardinality($1::text[]) AS owned
FROM chat_upload
WHERE owner_id = $2::int
  AND object_key = ANY($1::text[])
`

type CheckChatUploadOwnershipParams struct {
	ObjectKeys []string
	OwnerID    int32
}

func (q *Queries) CheckChatUploadOwnership(ctx context.Context, arg CheckChatUploadOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkChatUploadOwnership, arg.ObjectKeys, arg.OwnerID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const checkParticipantExists = `-- name: CheckParticipantExists :one
SELECT EXISTS(
    SELECT 1 FROM conversation_participant 
    WHERE conversation_id = $1 AND user_id = $2
)::boolean
`

type CheckParticipantExistsParams struct {
	ConversationID int64
	UserID         int32
}

func (q *Queries) CheckParticipantExists(ctx context.Context, arg CheckParticipantExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkParticipantExists, arg.ConversationID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const claimAttachmentModerationJobs = `-- name: ClaimAttachmentModerationJobs :many
WITH due AS (
  SELECT id FROM attachment_moderation_job
  WHERE status = 'queued' AND next_attempt_at <= now()
  ORDER BY id
  FOR UPDATE SKIP LOCKED
  LIMIT $1
)
UPDATE attachment_moderation_job j
SET status = 'processing', attempts = attempts + 1, updated_at = now()
FROM due
WHERE j.id = due.id
RETURNING j.id, j.attachment_id, j.message_id, j.conversation_id,
          j.object_key, j.mime_type, j.kind, j.attempts
`

type ClaimAttachmentModerationJobsRow struct {
	ID             int64
	AttachmentID   int64
	MessageID      int64
	ConversationID int64
	ObjectKey      string
	MimeType       string
	Kind           string
	Attempts       int32
}

// Отбор пачки задач. FOR UPDATE SKIP LOCKED — чтобы несколько воркеров могли
// работать параллельно, не разбирая одну задачу дважды.
func (q *Queries) ClaimAttachmentModerationJobs(ctx context.Context, batchSize int32) ([]ClaimAttachmentModerationJobsRow, error) {
	rows, err := q.db.Query(ctx, claimAttachmentModerationJobs, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimAttachmentModerationJobsRow
	for rows.Next() {
		var i ClaimAttachmentModerationJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.AttachmentID,
			&i.MessageID,
			&i.ConversationID,
			&i.ObjectKey,
			&i.MimeType,
			&i.Kind,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeAttachmentModeration = `-- name: CompleteAttachmentModeration :exec
UPDATE attachment_moderation_job
SET status = 'done',
    decision = $1,
    category = $2,
    reason = $3,
    confidence = $4,
    frames_checked = $5,
    last_error = NULL,
    updated_at = now()
WHERE id = $6
`

type CompleteAttachmentModerationParams struct {
	Decision      *string
	Category      *string
	Reason        *string
	Confidence    *float32
	FramesChecked *int32
	JobID         int64
}

func (q *Queries) CompleteAttachmentModeration(ctx context.Context, arg CompleteAttachmentModerationParams) error {
	_, err := q.db.Exec(ctx, completeAttachmentModeration,
		arg.Decision,
		arg.Category,
		arg.Reason,
		arg.Confidence,
		arg.FramesChecked,
		arg.JobID,
	)
	return err
}

const countPendingAttachments = `-- name: CountPendingAttachments :one
SELECT COUNT(*)::bigint FROM message_attachment
WHERE message_id = $1 AND moderation_status = 'pending'
`

// Сколько вложений сообщения ещё проверяется. Ноль означает, что сообщение
// можно доставлять получателю.
func (q *Queries) CountPendingAttachments(ctx context.Context, messageID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAttachments, messageID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAttachment = `-- name: CreateAttachment :one
WITH owned_upload AS (
  -- Record authoritative S3 metadata and lock the upload row until the
  -- surrounding message transaction commits.
  UPDATE chat_upload
  SET size_bytes = COALESCE($5, chat_upload.size_bytes),
      mime_type = COALESCE($4, chat_upload.mime_type)
  WHERE object_key = $11
    AND owner_id = $12::int
    AND sealed_key = $2
    AND content_etag IS NOT NULL
  RETURNING object_key
)
INSERT INTO message_attachment (
  message_id, url, file_name, mime_type, size_bytes, width, height,
  moderation_status, duration_seconds, thumbnail_url, upload_key
)
SELECT
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  owned_upload.object_key
FROM owned_upload
RETURNING id, message_id, url, file_name, mime_type, size_bytes, width, height,
          moderation_status, duration_seconds, thumbnail_url
`

type CreateAttachmentParams struct {
	MessageID        int64
	Url              string
	FileName         *string
	MimeType         *string
	SizeBytes        *int64
	Width            *int32
	Height           *int32
	ModerationStatus string
	DurationSeconds  *int32
	ThumbnailUrl     *string
	UploadKey        string
	OwnerID          int32
}

type CreateAttachmentRow struct {
	ID               int64
	MessageID        int64
	Url              string
	FileName         *string
	MimeType         *string
	SizeBytes        *int64
	Width            *int32
	Height           *int32
	ModerationStatus string
	DurationSeconds  *int32
	ThumbnailUrl     *string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.MessageID,
		arg.Url,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.ModerationStatus,
		arg.DurationSeconds,
		arg.ThumbnailUrl,
		arg.UploadKey,
		arg.OwnerID,
	)
	var i CreateAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Url,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.ModerationStatus,
		&i.DurationSeconds,
		&i.ThumbnailUrl,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversation (house_id, created_at, updated_at)
VALUES ($1, now(), now())
RETURNING id, house_id, created_at, updated_at
`

func (q *Queries) CreateConversation(ctx context.Context, houseID *int32) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, houseID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (conversation_id, sender_id, body, reply_to_message_id, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, conversation_id, sender_id, body, reply_to_message_id, created_at
`

type CreateMessageParams struct {
	ConversationID   int64
	SenderID         *int32
	Body             *string
	ReplyToMessageID *int64
}

type CreateMessageRow struct {
	ID               int64
	ConversationID   int64
	SenderID         *int32
	Body             *string
	ReplyToMessageID *int64
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Body,
		arg.ReplyToMessageID,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.ReplyToMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessageAttachments = `-- name: DeleteMessageAttachments :exec
DELETE FROM message_attachment
WHERE message_id = $1
`

// Legacy rows and registered references are removed together. The caller gets
// deletable S3 keys from DeleteOrphanedChatUploads, never from this statement.
func (q *Queries) DeleteMessageAttachments(ctx context.Context, messageID int64) error {
	_, err := q.db.Exec(ctx, deleteMessageAttachments, messageID)
	return err
}

const deleteOrphanedChatUploads = `-- name: DeleteOrphanedChatUploads :many
DELETE FROM chat_upload cu
WHERE cu.object_key = ANY($1::text[])
  AND NOT EXISTS (
    SELECT 1
    FROM message_attachment ma
    WHERE ma.upload_key = cu.object_key
  )
RETURNING cu.object_key, cu.sealed_key
`

type DeleteOrphanedChatUploadsRow struct {
	ObjectKey string
	SealedKey *string
}

func (q *Queries) DeleteOrphanedChatUploads(ctx context.Context, objectKeys []string) ([]DeleteOrphanedChatUploadsRow, error) {
	rows, err := q.db.Query(ctx, deleteOrphanedChatUploads, objectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteOrphanedChatUploadsRow
	for rows.Next() {
		var i DeleteOrphanedChatUploadsRow
		if err := rows.Scan(&i.ObjectKey, &i.SealedKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueAttachmentModeration = `-- name: EnqueueAttachmentModeration :exec
INSERT INTO attachment_moderation_job (
  attachment_id, message_id, conversation_id, object_key, mime_type, kind
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (attachment_id) DO NOTHING
`

type EnqueueAttachmentModerationParams struct {
	AttachmentID   int64
	MessageID      int64
	ConversationID int64
	ObjectKey      string
	MimeType       string
	Kind           string
}

// Ставит вложение в очередь проверки. Повторная постановка того же вложения —
// не ошибка (UNIQUE по attachment_id), а no-op: сообщение могли переотправить.
func (q *Queries) EnqueueAttachmentModeration(ctx context.Context, arg EnqueueAttachmentModerationParams) error {
	_, err := q.db.Exec(ctx, enqueueAttachmentModeration,
		arg.AttachmentID,
		arg.MessageID,
		arg.ConversationID,
		arg.ObjectKey,
		arg.MimeType,
		arg.Kind,
	)
	return err
}

const getChatUploads = `-- name: GetChatUploads :many
SELECT object_key, owner_id, size_bytes, mime_type, sealed_key, content_etag, created_at
FROM chat_upload
WHERE owner_id = $1::int
  AND object_key = ANY($2::text[])
ORDER BY object_key
`

type GetChatUploadsParams struct {
	OwnerID    int32
	ObjectKeys []string
}

type GetChatUploadsRow struct {
	ObjectKey   string
	OwnerID     *int32
	SizeBytes   int64
	MimeType    string
	SealedKey   *string
	ContentEtag *string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetChatUploads(ctx context.Context, arg GetChatUploadsParams) ([]GetChatUploadsRow, error) {
	rows, err := q.db.Query(ctx, getChatUploads, arg.OwnerID, arg.ObjectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatUploadsRow
	for rows.Next() {
		var i GetChatUploadsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.OwnerID,
			&i.SizeBytes,
			&i.MimeType,
			&i.SealedKey,
			&i.ContentEtag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationByParticipantsAndHouse = `-- name: GetConversationByParticipantsAndHouse :one
SELECT c.id
FROM conversation c
JOIN conversation_participant cp1 ON c.id = cp1.conversation_id
JOIN conversation_participant cp2 ON c.id = cp2.conversation_id
WHERE c.house_id = $1
  AND cp1.user_id = $2
  AND cp2.user_id = $3
  AND cp1.user_id <> cp2.user_id
LIMIT 1
`

type GetConversationByParticipantsAndHouseParams struct {
	HouseID  *int32
	UserID   int32
	UserID_2 int32
}

// 1. Поиск диалога привязанного к объекту (house_id IS NOT NULL)
func (q *Queries) GetConversationByParticipantsAndHouse(ctx context.Context, arg GetConversationByParticipantsAndHouseParams) (int64, error) {
	row := q.db.QueryRow(ctx, getConversationByParticipantsAndHouse, arg.HouseID, arg.UserID, arg.UserID_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConversationByParticipantsGeneral = `-- name: GetConversationByParticipantsGeneral :one
SELECT c.id
FROM conversation c
JOIN conversation_participant cp1 ON c.id = cp1.conversation_id
JOIN conversation_participant cp2 ON c.id = cp2.conversation_id
WHERE c.house_id IS NULL
  AND cp1.user_id = $1
  AND cp2.user_id = $2
  AND cp1.user_id <> cp2.user_id
LIMIT 1
`

type GetConversationByParticipantsGeneralParams struct {
	UserID   int32
	UserID_2 int32
}

// 2. Поиск общего диалога между пользователями (house_id IS NULL)
func (q *Queries) GetConversationByParticipantsGeneral(ctx context.Context, arg GetConversationByParticipantsGeneralParams) (int64, error) {
	row := q.db.QueryRow(ctx, getConversationByParticipantsGeneral, arg.UserID, arg.UserID_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT id, conversation_id, sender_id, body, reply_to_message_id, edited_at, deleted_at, created_at
FROM message
WHERE conversation_id = $1
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type GetConversationMessagesParams struct {
	ConversationID int64
	Column2        int64
	Limit          int32
}

type GetConversationMessagesRow struct {
	ID               int64
	ConversationID   int64
	SenderID         *int32
	Body             *string
	ReplyToMessageID *int64
	EditedAt         pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, arg.ConversationID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.ReplyToMessageID,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageAttachments = `-- name: GetMessageAttachments :many
SELECT id, message_id, url, file_name, mime_type, size_bytes, width, height,
       moderation_status, moderation_reason, duration_seconds, thumbnail_url
FROM message_attachment
WHERE message_id = ANY($1::bigint[])
`

type GetMessageAttachmentsRow struct {
	ID               int64
	MessageID        int64
	Url              string
	FileName         *string
	MimeType         *string
	SizeBytes        *int64
	Width            *int32
	Height           *int32
	ModerationStatus string
	ModerationReason *string
	DurationSeconds  *int32
	ThumbnailUrl     *string
}

func (q *Queries) GetMessageAttachments(ctx context.Context, dollar_1 []int64) ([]GetMessageAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, getMessageAttachments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageAttachmentsRow
	for rows.Next() {
		var i GetMessageAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Url,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.ModerationStatus,
			&i.ModerationReason,
			&i.DurationSeconds,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, conversation_id, sender_id, kind, payload, body,
       reply_to_message_id, edited_at, deleted_at, created_at
FROM message
WHERE id = $1
`

type GetMessageByIDRow struct {
	ID               int64
	ConversationID   int64
	SenderID         *int32
	Kind             string
	Payload          []byte
	Body             *string
	ReplyToMessageID *int64
	EditedAt         pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

// Одно сообщение целиком. Нужно воркеру модерации: после вердикта он публикует
// сообщение, которое при отправке было скрыто от получателя.
func (q *Queries) GetMessageByID(ctx context.Context, id int64) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Kind,
		&i.Payload,
		&i.Body,
		&i.ReplyToMessageID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageConversation = `-- name: GetMessageConversation :one
SELECT conversation_id FROM message WHERE id = $1
`

// Беседа процитированного сообщения — для проверки, что реплай не ссылается на
// чужой диалог.
func (q *Queries) GetMessageConversation(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getMessageConversation, id)
	var conversation_id int64
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getMessageForMutation = `-- name: GetMessageForMutation :one
SELECT
    m.id,
    m.conversation_id,
    m.sender_id,
    m.kind,
    m.body,
    m.created_at,
    m.edited_at,
    m.deleted_at,
    (SELECT COUNT(*) FROM message_attachment ma WHERE ma.message_id = m.id) AS attachment_count,
    COALESCE((
        SELECT MAX(cp.last_read_message_id)
        FROM conversation_participant cp
        WHERE cp.conversation_id = m.conversation_id
          AND cp.user_id <> $1::int
    ), 0)::bigint AS other_last_read_message_id
FROM message m
WHERE m.id = $2
`

type GetMessageForMutationParams struct {
	UserID    int32
	MessageID int64
}

type GetMessageForMutationRow struct {
	ID                     int64
	ConversationID         int64
	SenderID               *int32
	Kind                   string
	Body                   *string
	CreatedAt              pgtype.Timestamptz
	EditedAt               pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	AttachmentCount        int64
	OtherLastReadMessageID int64
}

// Сообщение с данными, нужными для проверки прав на правку и удаление:
// автор, время создания, наличие вложений и позиция курсора прочтения у
// собеседника. Всё одним запросом, чтобы не гонять три round trip перед
// отказом.
func (q *Queries) GetMessageForMutation(ctx context.Context, arg GetMessageForMutationParams) (GetMessageForMutationRow, error) {
	row := q.db.QueryRow(ctx, getMessageForMutation, arg.UserID, arg.MessageID)
	var i GetMessageForMutationRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Kind,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.AttachmentCount,
		&i.OtherLastReadMessageID,
	)
	return i, err
}

const getMessageQuotes = `-- name: GetMessageQuotes :many
SELECT
    m.id,
    m.sender_id,
    m.kind,
    m.deleted_at,
    LEFT(COALESCE(m.body, ''), $1::int)::text AS body_preview,
    (
        SELECT COUNT(*)
        FROM message_attachment ma
        WHERE ma.message_id = m.id
          AND ma.moderation_status = 'approved'
    ) AS attachment_count,
    COALESCE((
        SELECT ma.url
        FROM message_attachment ma
        WHERE ma.message_id = m.id
          AND ma.moderation_status = 'approved'
          AND ma.mime_type LIKE 'image/%'
        ORDER BY ma.id
        LIMIT 1
    ), '')::text AS first_image_url
FROM message m
WHERE m.id = ANY($2::bigint[])
`

type GetMessageQuotesParams struct {
	PreviewLimit int32
	Ids          []int64
}

type GetMessageQuotesRow struct {
	ID              int64
	SenderID        *int32
	Kind            string
	DeletedAt       pgtype.Timestamptz
	BodyPreview     string
	AttachmentCount int64
	FirstImageUrl   string
}

// Компактные данные процитированных сообщений для гидрации реплаев.
// Тело обрезается в SQL: цитата рендерится одной-двумя строками, и тащить
// полные 4000 символов на каждую страницу истории незачем.
// Первое вложение берётся коррелированным подзапросом по возрастанию id —
// нужен только превью-URL, а не весь список.
func (q *Queries) GetMessageQuotes(ctx context.Context, arg GetMessageQuotesParams) ([]GetMessageQuotesRow, error) {
	rows, err := q.db.Query(ctx, getMessageQuotes, arg.PreviewLimit, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageQuotesRow
	for rows.Next() {
		var i GetMessageQuotesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Kind,
			&i.DeletedAt,
			&i.BodyPreview,
			&i.AttachmentCount,
			&i.FirstImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOtherParticipantID = `-- name: GetOtherParticipantID :one
SELECT user_id::int FROM conversation_participant
WHERE conversation_id = $1 AND user_id <> $2
LIMIT 1
`

type GetOtherParticipantIDParams struct {
	ConversationID int64
	UserID         int32
}

func (q *Queries) GetOtherParticipantID(ctx context.Context, arg GetOtherParticipantIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOtherParticipantID, arg.ConversationID, arg.UserID)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const getRecentMessagesForSuggestions = `-- name: GetRecentMessagesForSuggestions :many
SELECT sender_id, kind, COALESCE(body, '')::text AS body
FROM message
WHERE conversation_id = $1
  AND deleted_at IS NULL
ORDER BY id DESC
LIMIT $2
`

type GetRecentMessagesForSuggestionsParams struct {
	ConversationID int64
	Limit          int32
}

type GetRecentMessagesForSuggestionsRow struct {
	SenderID *int32
	Kind     string
	Body     string
}

// Последние сообщения беседы для промпта. Удалённые пропускаем: их текста уже
// нет, а подсказка по пустому сообщению смысла не имеет.
func (q *Queries) GetRecentMessagesForSuggestions(ctx context.Context, arg GetRecentMessagesForSuggestionsParams) ([]GetRecentMessagesForSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, getRecentMessagesForSuggestions, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMessagesForSuggestionsRow
	for rows.Next() {
		var i GetRecentMessagesForSuggestionsRow
		if err := rows.Scan(&i.SenderID, &i.Kind, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuggestionContext = `-- name: GetSuggestionContext :one
SELECT
    c.house_id,
    COALESCE(h.owner_id, 0)::int AS owner_id,
    COALESCE(h.city, '')::text AS city,
    COALESCE(h.street, '')::text AS street,
    COALESCE(h.count_room, '')::text AS count_room,
    COALESCE(h.price, 0)::int AS price,
    COALESCE(h.max_guests, 0)::int AS max_guests,
    to_char(h.check_in_after, 'HH24:MI') AS check_in_after,
    to_char(h.check_out_before, 'HH24:MI') AS check_out_before,
    COALESCE((SELECT MAX(m.id) FROM message m WHERE m.conversation_id = c.id), 0)::bigint AS last_message_id
FROM conversation c
LEFT JOIN house h ON h.id = c.house_id
WHERE c.id = $1
`

type GetSuggestionContextRow struct {
	HouseID        *int32
	OwnerID        int32
	City           string
	Street         string
	CountRoom      string
	Price          int32
	MaxGuests      int32
	CheckInAfter   string
	CheckOutBefore string
	LastMessageID  int64
}

// Контекст беседы для ИИ-подсказок: объявление, роль запрашивающего и курсор
// последнего сообщения. Один запрос вместо трёх — подсказки запрашиваются при
// каждом открытии чата, и лишние round trip тут заметны.
func (q *Queries) GetSuggestionContext(ctx context.Context, id int64) (GetSuggestionContextRow, error) {
	row := q.db.QueryRow(ctx, getSuggestionContext, id)
	var i GetSuggestionContextRow
	err := row.Scan(
		&i.HouseID,
		&i.OwnerID,
		&i.City,
		&i.Street,
		&i.CountRoom,
		&i.Price,
		&i.MaxGuests,
		&i.CheckInAfter,
		&i.CheckOutBefore,
		&i.LastMessageID,
	)
	return i, err
}

const getUserMediaStanding = `-- name: GetUserMediaStanding :one
SELECT phone_verified_at, created_at::timestamptz AS created_at
FROM "user"
WHERE id = $1
`

type GetUserMediaStandingRow struct {
	PhoneVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

// Данные аккаунта для гейта на видео: подтверждён ли телефон и когда создан.
// created_at в таблице user хранится без таймзоны — приводим к timestamptz,
// иначе сравнение возраста аккаунта зависит от таймзоны сессии.
func (q *Queries) GetUserMediaStanding(ctx context.Context, id int32) (GetUserMediaStandingRow, error) {
	row := q.db.QueryRow(ctx, getUserMediaStanding, id)
	var i GetUserMediaStandingRow
	err := row.Scan(&i.PhoneVerifiedAt, &i.CreatedAt)
	return i, err
}

const isOtherParticipantDeleted = `-- name: IsOtherParticipantDeleted :one
SELECT COALESCE(u.deleted, false)::boolean
FROM conversation_participant cp
JOIN "user" u ON cp.user_id = u.id
WHERE cp.conversation_id = $1 AND cp.user_id <> $2
LIMIT 1
`

type IsOtherParticipantDeletedParams struct {
	ConversationID int64
	UserID         int32
}

func (q *Queries) IsOtherParticipantDeleted(ctx context.Context, arg IsOtherParticipantDeletedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOtherParticipantDeleted, arg.ConversationID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT 
    c.id AS conversation_id,
    c.house_id,
    c.updated_at AS last_activity,
    cp.last_read_message_id,
    other_cp.last_read_message_id AS other_last_read_message_id,
    (
        SELECT COUNT(*)
        FROM message unread_m
        WHERE unread_m.conversation_id = c.id
          AND unread_m.id > cp.last_read_message_id
          AND (
            unread_m.sender_id = cp.user_id
            OR unread_m.sender_id IS NULL
            OR (
              NOT EXISTS (
                SELECT 1 FROM message_attachment pending_ma
                WHERE pending_ma.message_id = unread_m.id
                  AND pending_ma.moderation_status = 'pending'
              )
              AND (
                NOT EXISTS (
                  SELECT 1 FROM message_attachment any_ma
                  WHERE any_ma.message_id = unread_m.id
                )
                OR EXISTS (
                  SELECT 1 FROM message_attachment approved_ma
                  WHERE approved_ma.message_id = unread_m.id
                    AND approved_ma.moderation_status = 'approved'
                )
              )
            )
          )
    ) AS unread_count,
    m.id AS last_message_id,
    CASE
        WHEN m.deleted_at IS NOT NULL THEN 'Сообщение удалено'
        WHEN m.sender_id = cp.user_id
          AND EXISTS (
            SELECT 1 FROM message_attachment rejected_ma
            WHERE rejected_ma.message_id = m.id
              AND rejected_ma.moderation_status = 'rejected'
          )
          AND NOT EXISTS (
            SELECT 1 FROM message_attachment approved_ma
            WHERE approved_ma.message_id = m.id
              AND approved_ma.moderation_status = 'approved'
          )
          THEN COALESCE(m.body, '[Вложение не отправлено]')
        ELSE COALESCE(m.body, (
            SELECT CASE
                -- Альбом: показываем количество, а не «[Изображение]» —
                -- иначе отправка десяти фото в списке выглядит как одно.
                WHEN COUNT(*) FILTER (WHERE ma.mime_type LIKE 'image/%') > 1
                    THEN '[Фото: ' || COUNT(*) FILTER (WHERE ma.mime_type LIKE 'image/%') || ']'
                WHEN COUNT(*) FILTER (WHERE ma.mime_type LIKE 'image/%') = 1
                    THEN '[Изображение]'
                ELSE '[Документ]: ' || COALESCE(MIN(ma.file_name), '')
            END
            FROM message_attachment ma
            WHERE ma.message_id = m.id
              AND ma.moderation_status = 'approved'
        ), '')
    END::text AS last_message_body,
    m.sender_id AS last_message_sender_id,
    m.created_at AS last_message_created_at,
    other_u.id AS other_user_id,
    other_u.name AS other_user_name,
    other_u.surname AS other_user_surname,
    other_u.avatar_url AS other_user_avatar_url,
    other_u.phone AS other_user_phone,
    other_u.deleted AS other_user_deleted,
    h.street AS house_street,
    h.house_number AS house_number,
    h.count_room AS house_count_room,
    h.price AS house_price,
    COALESCE((
        SELECT f.path
        FROM file f
        WHERE f.house_id = h.id AND f.deleted = false
        ORDER BY f.position
        LIMIT 1
    ), '')::text AS house_cover_path
FROM conversation c
JOIN conversation_participant cp ON c.id = cp.conversation_id
JOIN conversation_participant other_cp ON c.id = other_cp.conversation_id AND other_cp.user_id <> cp.user_id
JOIN "user" other_u ON other_cp.user_id = other_u.id
LEFT JOIN house h ON c.house_id = h.id
LEFT JOIN message m ON m.conversation_id = c.id AND m.id = (
    SELECT MAX(candidate.id)
    FROM message candidate
    WHERE candidate.conversation_id = c.id
      AND (
        candidate.sender_id = cp.user_id
        OR candidate.sender_id IS NULL
        OR (
          NOT EXISTS (
            SELECT 1 FROM message_attachment pending_ma
            WHERE pending_ma.message_id = candidate.id
              AND pending_ma.moderation_status = 'pending'
          )
          AND (
            NOT EXISTS (
              SELECT 1 FROM message_attachment any_ma
              WHERE any_ma.message_id = candidate.id
            )
            OR EXISTS (
              SELECT 1 FROM message_attachment approved_ma
              WHERE approved_ma.message_id = candidate.id
                AND approved_ma.moderation_status = 'approved'
            )
          )
        )
      )
)
WHERE cp.user_id = $1
ORDER BY c.updated_at DESC
`

type ListUserConversationsRow struct {
	ConversationID         int64
	HouseID                *int32
	LastActivity           pgtype.Timestamptz
	LastReadMessageID      *int64
	OtherLastReadMessageID *int64
	UnreadCount            int64
	LastMessageID          *int64
	LastMessageBody        string
	LastMessageSenderID    *int32
	LastMessageCreatedAt   pgtype.Timestamptz
	OtherUserID            int32
	OtherUserName          *string
	OtherUserSurname       *string
	OtherUserAvatarUrl     *string
	OtherUserPhone         *string
	OtherUserDeleted       bool
	HouseStreet            *string
	HouseNumber            *string
	HouseCountRoom         *string
	HousePrice             *int32
	HouseCoverPath         string
}

// Тянет последнее сообщение с Фолбэком для медиа-вложений (превью в списке диалогов)
func (q *Queries) ListUserConversations(ctx context.Context, userID int32) ([]ListUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, listUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserConversationsRow
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.HouseID,
			&i.LastActivity,
			&i.LastReadMessageID,
			&i.OtherLastReadMessageID,
			&i.UnreadCount,
			&i.LastMessageID,
			&i.LastMessageBody,
			&i.LastMessageSenderID,
			&i.LastMessageCreatedAt,
			&i.OtherUserID,
			&i.OtherUserName,
			&i.OtherUserSurname,
			&i.OtherUserAvatarUrl,
			&i.OtherUserPhone,
			&i.OtherUserDeleted,
			&i.HouseStreet,
			&i.HouseNumber,
			&i.HouseCountRoom,
			&i.HousePrice,
			&i.HouseCoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttachmentUpload = `-- name: LockAttachmentUpload :one
SELECT cu.object_key
FROM chat_upload cu
JOIN message_attachment ma ON ma.upload_key = cu.object_key
WHERE ma.id = $1
FOR UPDATE OF cu
`

func (q *Queries) LockAttachmentUpload(ctx context.Context, attachmentID int64) (string, error) {
	row := q.db.QueryRow(ctx, lockAttachmentUpload, attachmentID)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const lockMessageAttachmentUploads = `-- name: LockMessageAttachmentUploads :many
SELECT cu.object_key
FROM chat_upload cu
JOIN (
  SELECT DISTINCT upload_key
  FROM message_attachment
  WHERE message_id = $1
    AND upload_key IS NOT NULL
) refs ON refs.upload_key = cu.object_key
ORDER BY cu.object_key
FOR UPDATE OF cu
`

// Lock registered uploads in a stable order before removing references.
func (q *Queries) LockMessageAttachmentUploads(ctx context.Context, messageID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, lockMessageAttachmentUploads, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerChatUpload = `-- name: RegisterChatUpload :exec
INSERT INTO chat_upload (object_key, owner_id, size_bytes, mime_type)
VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type RegisterChatUploadParams struct {
	ObjectKey string
	OwnerID   *int32
	SizeBytes int64
	MimeType  string
}

func (q *Queries) RegisterChatUpload(ctx context.Context, arg RegisterChatUploadParams) error {
	_, err := q.db.Exec(ctx, registerChatUpload,
		arg.ObjectKey,
		arg.OwnerID,
		arg.SizeBytes,
		arg.MimeType,
	)
	return err
}

const rejectAttachment = `-- name: RejectAttachment :exec
UPDATE message_attachment
SET moderation_status = 'rejected',
    moderation_reason = LEFT($1, 500),
    url = '',
    thumbnail_url = NULL,
    upload_key = NULL
WHERE id = $2
`

type RejectAttachmentParams struct {
	ModerationReason string
	AttachmentID     int64
}

// Keep a sender-only tombstone with the reason, but detach every reference to
// the unsafe object before it is removed from storage.
func (q *Queries) RejectAttachment(ctx context.Context, arg RejectAttachmentParams) error {
	_, err := q.db.Exec(ctx, rejectAttachment, arg.ModerationReason, arg.AttachmentID)
	return err
}

const releaseStaleAttachmentJobs = `-- name: ReleaseStaleAttachmentJobs :exec
UPDATE attachment_moderation_job
SET status = 'queued',
    last_error = 'processing lease expired',
    updated_at = now()
WHERE status = 'processing'
  AND updated_at < now() - $1::interval
`

// Возвращает в очередь задачи, которые воркер взял и не завершил: процесс мог
// умереть посреди нарезки кадров. Без этого задача залипает в processing
// навсегда, а вложение — в pending, то есть получатель его никогда не увидит.
func (q *Queries) ReleaseStaleAttachmentJobs(ctx context.Context, lease pgtype.Interval) error {
	_, err := q.db.Exec(ctx, releaseStaleAttachmentJobs, lease)
	return err
}

const retryAttachmentModeration = `-- name: RetryAttachmentModeration :exec
UPDATE attachment_moderation_job
SET status = 'queued',
    next_attempt_at = $1,
    last_error = $2,
    updated_at = now()
WHERE id = $3
`

type RetryAttachmentModerationParams struct {
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
	JobID         int64
}

// Инфраструктурный сбой (модель недоступна, ffmpeg упал): задача возвращается в
// очередь с отложенной попыткой. Вложение остаётся pending, то есть не
// публикуется — при недоступной проверке безопаснее задержать, чем пропустить.
func (q *Queries) RetryAttachmentModeration(ctx context.Context, arg RetryAttachmentModerationParams) error {
	_, err := q.db.Exec(ctx, retryAttachmentModeration, arg.NextAttemptAt, arg.LastError, arg.JobID)
	return err
}

const sealChatUpload = `-- name: SealChatUpload :one
UPDATE chat_upload
SET sealed_key = $1,
    content_etag = $2
WHERE object_key = $3
  AND owner_id = $4::int
  AND (
    sealed_key IS NULL OR
    (sealed_key = $1 AND content_etag = $2)
  )
RETURNING object_key
`

type SealChatUploadParams struct {
	SealedKey   *string
	ContentEtag *string
	ObjectKey   string
	OwnerID     int32
}

func (q *Queries) SealChatUpload(ctx context.Context, arg SealChatUploadParams) (string, error) {
	row := q.db.QueryRow(ctx, sealChatUpload,
		arg.SealedKey,
		arg.ContentEtag,
		arg.ObjectKey,
		arg.OwnerID,
	)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const setAttachmentModerationStatus = `-- name: SetAttachmentModerationStatus :exec
UPDATE message_attachment
SET moderation_status = $1
WHERE id = $2
`

type SetAttachmentModerationStatusParams struct {
	ModerationStatus string
	AttachmentID     int64
}

func (q *Queries) SetAttachmentModerationStatus(ctx context.Context, arg SetAttachmentModerationStatusParams) error {
	_, err := q.db.Exec(ctx, setAttachmentModerationStatus, arg.ModerationStatus, arg.AttachmentID)
	return err
}

const setAttachmentVideoMeta = `-- name: SetAttachmentVideoMeta :exec
UPDATE message_attachment
SET duration_seconds = $1,
    thumbnail_url = $2
WHERE id = $3
`

type SetAttachmentVideoMetaParams struct {
	DurationSeconds *int32
	ThumbnailUrl    *string
	AttachmentID    int64
}

// Длительность и обложка становятся известны только после probe на сервере:
// заявленным клиентом значениям доверять нельзя.
func (q *Queries) SetAttachmentVideoMeta(ctx context.Context, arg SetAttachmentVideoMetaParams) error {
	_, err := q.db.Exec(ctx, setAttachmentVideoMeta, arg.DurationSeconds, arg.ThumbnailUrl, arg.AttachmentID)
	return err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE message
SET deleted_at = now(), body = NULL
WHERE id = $1
  AND sender_id = $2::int
  AND kind = 'user'
  AND deleted_at IS NULL
  AND created_at > now() - $3::interval
RETURNING id, conversation_id, sender_id, body, reply_to_message_id, edited_at, deleted_at, created_at
`

type SoftDeleteMessageParams struct {
	MessageID    int64
	UserID       int32
	DeleteWindow pgtype.Interval
}

type SoftDeleteMessageRow struct {
	ID               int64
	ConversationID   int64
	SenderID         *int32
	Body             *string
	ReplyToMessageID *int64
	EditedAt         pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

// Мягкое удаление: строка остаётся (иначе порвутся цитаты в ответах и
// разъедется last_read_message_id), но тело обнуляется, чтобы удалённый текст
// не оставался в базе.
func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (SoftDeleteMessageRow, error) {
	row := q.db.QueryRow(ctx, softDeleteMessage, arg.MessageID, arg.UserID, arg.DeleteWindow)
	var i SoftDeleteMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.ReplyToMessageID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateConversationTimestamp = `-- name: UpdateConversationTimestamp :exec
UPDATE conversation
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateConversationTimestamp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateConversationTimestamp, id)
	return err
}

const updateLastReadMessage = `-- name: UpdateLastReadMessage :exec
UPDATE conversation_participant
SET last_read_message_id = $1, last_read_at = now()
WHERE conversation_id = $2 AND user_id = $3
`

type UpdateLastReadMessageParams struct {
	LastReadMessageID *int64
	ConversationID    int64
	UserID            int32
}

func (q *Queries) UpdateLastReadMessage(ctx context.Context, arg UpdateLastReadMessageParams) error {
	_, err := q.db.Exec(ctx, updateLastReadMessage, arg.LastReadMessageID, arg.ConversationID, arg.UserID)
	return err
}

const updateMessageBody = `-- name: UpdateMessageBody :one
UPDATE message
SET body = $1, edited_at = now()
WHERE id = $2
  AND sender_id = $3::int
  AND kind = 'user'
  AND deleted_at IS NULL
  AND created_at > now() - $4::interval
RETURNING id, conversation_id, sender_id, body, reply_to_message_id, edited_at, deleted_at, created_at
`

type UpdateMessageBodyParams struct {
	Body       *string
	MessageID  int64
	UserID     int32
	EditWindow pgtype.Interval
}

type UpdateMessageBodyRow struct {
	ID               int64
	ConversationID   int64
	SenderID         *int32
	Body             *string
	ReplyToMessageID *int64
	EditedAt         pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

// Правка тела. Условия в WHERE, а не только в Go: параллельный запрос не должен
// проскочить между проверкой и записью. Пустой результат = правка не разрешена.
func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (UpdateMessageBodyRow, error) {
	row := q.db.QueryRow(ctx, updateMessageBody,
		arg.Body,
		arg.MessageID,
		arg.UserID,
		arg.EditWindow,
	)
	var i UpdateMessageBodyRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.ReplyToMessageID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
