// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorite (user_id, house_id, created_at)
VALUES ($1::int, $2::int, now())
ON CONFLICT (user_id, house_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID  int32
	HouseID int32
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.HouseID)
	return err
}

const countFavoriteHouses = `-- name: CountFavoriteHouses :one
SELECT count(*)
FROM favorite fav
JOIN house h ON h.id = fav.house_id
WHERE fav.user_id = $1::int
  AND h.deleted = false
  AND h.status = 'active'
`

func (q *Queries) CountFavoriteHouses(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteHouses, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const houseExists = `-- name: HouseExists :one
SELECT EXISTS (
  SELECT 1 FROM house WHERE id = $1::int AND deleted = false
)
`

func (q *Queries) HouseExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, houseExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavoriteHouses = `-- name: ListFavoriteHouses :many
SELECT
  h.id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.area,
  h.country,
  h.status,
  h.lat,
  h.lng,
  h.views,
  h.created_at,
  COALESCE((
    SELECT f.path
    FROM file f
    WHERE f.house_id = h.id AND f.deleted = false
    ORDER BY f.position
    LIMIT 1
  ), '')::text AS cover_path
FROM favorite fav
JOIN house h ON h.id = fav.house_id
WHERE fav.user_id = $1::int
  AND h.deleted = false
  AND h.status = 'active'
ORDER BY fav.created_at DESC
LIMIT $3 OFFSET $2
`

type ListFavoriteHousesParams struct {
	UserID       int32
	ResultOffset int32
	ResultLimit  int32
}

type ListFavoriteHousesRow struct {
	ID          int32
	Street      string
	HouseNumber string
	Description string
	Price       int32
	CountRoom   string
	Area        int32
	Country     string
	Status      string
	Lat         *float64
	Lng         *float64
	Views       int32
	CreatedAt   pgtype.Timestamp
	CoverPath   string
}

func (q *Queries) ListFavoriteHouses(ctx context.Context, arg ListFavoriteHousesParams) ([]ListFavoriteHousesRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteHouses, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoriteHousesRow
	for rows.Next() {
		var i ListFavoriteHousesRow
		if err := rows.Scan(
			&i.ID,
			&i.Street,
			&i.HouseNumber,
			&i.Description,
			&i.Price,
			&i.CountRoom,
			&i.Area,
			&i.Country,
			&i.Status,
			&i.Lat,
			&i.Lng,
			&i.Views,
			&i.CreatedAt,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteIDs = `-- name: ListFavoriteIDs :many
SELECT house_id
FROM favorite
WHERE user_id = $1::int
ORDER BY created_at DESC
`

func (q *Queries) ListFavoriteIDs(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listFavoriteIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var house_id int32
		if err := rows.Scan(&house_id); err != nil {
			return nil, err
		}
		items = append(items, house_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorite
WHERE user_id = $1::int AND house_id = $2::int
`

type RemoveFavoriteParams struct {
	UserID  int32
	HouseID int32
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.HouseID)
	return err
}
