// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHousesFiltered = `-- name: CountHousesFiltered :one
SELECT count(*)
FROM house h
WHERE h.deleted = false
  AND h.status = 'active'
  AND (
    $1::text IS NULL
    OR h.street ILIKE '%' || $1 || '%'
    OR h.house_number ILIKE '%' || $1 || '%'
    OR h.description ILIKE '%' || $1 || '%'
    OR h.country ILIKE '%' || $1 || '%'
  )
  AND ($2::text IS NULL OR h.country = $2)
  AND ($3::int IS NULL OR h.price >= $3)
  AND ($4::int IS NULL OR h.price <= $4)
  AND (
    (cardinality($5::int[]) = 0 AND $6::int IS NULL)
    OR (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) = ANY($5::int[])
    OR (
      $6::int IS NOT NULL
      AND (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) >= $6
    )
  )
  AND (
    cardinality($7::int[]) = 0
    OR (
      SELECT count(DISTINCT hhs.service_id)
      FROM house_house_service hhs
      WHERE hhs.house_id = h.id AND hhs.service_id = ANY($7::int[])
    ) = cardinality($7::int[])
  )
  AND (
    $8::int IS NULL
    OR EXISTS (
      SELECT 1 FROM house_house_category hhc
      WHERE hhc.house_id = h.id AND hhc.house_category_id = $8
    )
  )
`

type CountHousesFilteredParams struct {
	Query    *string
	City     *string
	PriceMin *int32
	PriceMax *int32
	Rooms    []int32
	RoomsMin *int32
	Services []int32
	Category *int32
}

func (q *Queries) CountHousesFiltered(ctx context.Context, arg CountHousesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHousesFiltered,
		arg.Query,
		arg.City,
		arg.PriceMin,
		arg.PriceMax,
		arg.Rooms,
		arg.RoomsMin,
		arg.Services,
		arg.Category,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHouseByID = `-- name: GetHouseByID :one
SELECT
  h.id,
  h.owner_id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.number_room,
  h.area,
  h.country,
  h.status,
  h.lat,
  h.lng,
  h.views,
  h.created_at,
  h.updated_at,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  ), 0)::float8 AS rating,
  (
    SELECT count(*)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  )::int AS reviews_count
FROM house h
WHERE h.id = $1 AND h.deleted = false
`

type GetHouseByIDRow struct {
	ID           int32
	OwnerID      int32
	Street       string
	HouseNumber  string
	Description  string
	Price        int32
	CountRoom    string
	NumberRoom   *string
	Area         int32
	Country      string
	Status       string
	Lat          *float64
	Lng          *float64
	Views        int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Rating       float64
	ReviewsCount int32
}

func (q *Queries) GetHouseByID(ctx context.Context, id int32) (GetHouseByIDRow, error) {
	row := q.db.QueryRow(ctx, getHouseByID, id)
	var i GetHouseByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Street,
		&i.HouseNumber,
		&i.Description,
		&i.Price,
		&i.CountRoom,
		&i.NumberRoom,
		&i.Area,
		&i.Country,
		&i.Status,
		&i.Lat,
		&i.Lng,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rating,
		&i.ReviewsCount,
	)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name
FROM house_category
WHERE deleted = false
ORDER BY name
`

type ListAllCategoriesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCategoriesRow
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllServices = `-- name: ListAllServices :many
SELECT id, name
FROM service
WHERE deleted = false
ORDER BY name
`

type ListAllServicesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListAllServices(ctx context.Context) ([]ListAllServicesRow, error) {
	rows, err := q.db.Query(ctx, listAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllServicesRow
	for rows.Next() {
		var i ListAllServicesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseCategories = `-- name: ListHouseCategories :many
SELECT c.id, c.name
FROM house_category c
JOIN house_house_category hhc ON hhc.house_category_id = c.id
WHERE hhc.house_id = $1 AND c.deleted = false
ORDER BY c.name
`

type ListHouseCategoriesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListHouseCategories(ctx context.Context, houseID int32) ([]ListHouseCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listHouseCategories, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseCategoriesRow
	for rows.Next() {
		var i ListHouseCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousePhotos = `-- name: ListHousePhotos :many
SELECT id, house_id, path, position
FROM file
WHERE house_id = $1 AND deleted = false
ORDER BY position
`

type ListHousePhotosRow struct {
	ID       int32
	HouseID  *int32
	Path     string
	Position int32
}

func (q *Queries) ListHousePhotos(ctx context.Context, houseID *int32) ([]ListHousePhotosRow, error) {
	rows, err := q.db.Query(ctx, listHousePhotos, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousePhotosRow
	for rows.Next() {
		var i ListHousePhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.Path,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseServices = `-- name: ListHouseServices :many
SELECT s.id, s.name
FROM service s
JOIN house_house_service hhs ON hhs.service_id = s.id
WHERE hhs.house_id = $1 AND s.deleted = false
ORDER BY s.name
`

type ListHouseServicesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListHouseServices(ctx context.Context, houseID int32) ([]ListHouseServicesRow, error) {
	rows, err := q.db.Query(ctx, listHouseServices, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseServicesRow
	for rows.Next() {
		var i ListHouseServicesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousesFiltered = `-- name: ListHousesFiltered :many
SELECT
  h.id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.area,
  h.country,
  h.status,
  h.lat,
  h.lng,
  h.views,
  h.created_at,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  ), 0)::float8 AS rating,
  (
    SELECT count(*)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  )::int AS reviews_count,
  COALESCE((
    SELECT f.path
    FROM file f
    WHERE f.house_id = h.id AND f.deleted = false
    ORDER BY f.position
    LIMIT 1
  ), '')::text AS cover_path
FROM house h
WHERE h.deleted = false
  AND h.status = 'active'
  AND (
    $1::text IS NULL
    OR h.street ILIKE '%' || $1 || '%'
    OR h.house_number ILIKE '%' || $1 || '%'
    OR h.description ILIKE '%' || $1 || '%'
    OR h.country ILIKE '%' || $1 || '%'
  )
  AND ($2::text IS NULL OR h.country = $2)
  AND ($3::int IS NULL OR h.price >= $3)
  AND ($4::int IS NULL OR h.price <= $4)
  AND (
    (cardinality($5::int[]) = 0 AND $6::int IS NULL)
    OR (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) = ANY($5::int[])
    OR (
      $6::int IS NOT NULL
      AND (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) >= $6
    )
  )
  AND (
    cardinality($7::int[]) = 0
    OR (
      SELECT count(DISTINCT hhs.service_id)
      FROM house_house_service hhs
      WHERE hhs.house_id = h.id AND hhs.service_id = ANY($7::int[])
    ) = cardinality($7::int[])
  )
  AND (
    $8::int IS NULL
    OR EXISTS (
      SELECT 1 FROM house_house_category hhc
      WHERE hhc.house_id = h.id AND hhc.house_category_id = $8
    )
  )
ORDER BY
  CASE WHEN $9::text = 'price_asc' THEN h.price END ASC NULLS LAST,
  CASE WHEN $9::text = 'price_desc' THEN h.price END DESC NULLS LAST,
  CASE WHEN $9::text = 'newest' THEN h.created_at END DESC NULLS LAST,
  h.date_top DESC NULLS LAST,
  h.created_at DESC
LIMIT $11 OFFSET $10
`

type ListHousesFilteredParams struct {
	Query        *string
	City         *string
	PriceMin     *int32
	PriceMax     *int32
	Rooms        []int32
	RoomsMin     *int32
	Services     []int32
	Category     *int32
	Sort         string
	ResultOffset int32
	ResultLimit  int32
}

type ListHousesFilteredRow struct {
	ID           int32
	Street       string
	HouseNumber  string
	Description  string
	Price        int32
	CountRoom    string
	Area         int32
	Country      string
	Status       string
	Lat          *float64
	Lng          *float64
	Views        int32
	CreatedAt    pgtype.Timestamp
	Rating       float64
	ReviewsCount int32
	CoverPath    string
}

func (q *Queries) ListHousesFiltered(ctx context.Context, arg ListHousesFilteredParams) ([]ListHousesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listHousesFiltered,
		arg.Query,
		arg.City,
		arg.PriceMin,
		arg.PriceMax,
		arg.Rooms,
		arg.RoomsMin,
		arg.Services,
		arg.Category,
		arg.Sort,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousesFilteredRow
	for rows.Next() {
		var i ListHousesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Street,
			&i.HouseNumber,
			&i.Description,
			&i.Price,
			&i.CountRoom,
			&i.Area,
			&i.Country,
			&i.Status,
			&i.Lat,
			&i.Lng,
			&i.Views,
			&i.CreatedAt,
			&i.Rating,
			&i.ReviewsCount,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
