// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHouseCategory = `-- name: AddHouseCategory :exec
INSERT INTO house_house_category (house_id, house_category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddHouseCategoryParams struct {
	HouseID         int32
	HouseCategoryID int32
}

func (q *Queries) AddHouseCategory(ctx context.Context, arg AddHouseCategoryParams) error {
	_, err := q.db.Exec(ctx, addHouseCategory, arg.HouseID, arg.HouseCategoryID)
	return err
}

const addHouseService = `-- name: AddHouseService :exec
INSERT INTO house_house_service (house_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddHouseServiceParams struct {
	HouseID   int32
	ServiceID int32
}

func (q *Queries) AddHouseService(ctx context.Context, arg AddHouseServiceParams) error {
	_, err := q.db.Exec(ctx, addHouseService, arg.HouseID, arg.ServiceID)
	return err
}

const countHousesByOwner = `-- name: CountHousesByOwner :one
SELECT count(*)
FROM house h
WHERE h.owner_id = $1 AND h.deleted = false
`

func (q *Queries) CountHousesByOwner(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countHousesByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHousesFiltered = `-- name: CountHousesFiltered :one
SELECT count(*)
FROM house h
WHERE h.deleted = false
  AND h.status = 'active'
  AND (
    $1::text IS NULL
    OR h.street ILIKE '%' || $1 || '%'
    OR h.house_number ILIKE '%' || $1 || '%'
    OR h.description ILIKE '%' || $1 || '%'
    OR h.country ILIKE '%' || $1 || '%'
  )
  AND ($2::text IS NULL OR h.country = $2)
  AND ($3::int IS NULL OR h.price >= $3)
  AND ($4::int IS NULL OR h.price <= $4)
  AND (
    (cardinality($5::int[]) = 0 AND $6::int IS NULL)
    OR (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) = ANY($5::int[])
    OR (
      $6::int IS NOT NULL
      AND (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) >= $6
    )
  )
  AND (
    cardinality($7::int[]) = 0
    OR (
      SELECT count(DISTINCT hhs.service_id)
      FROM house_house_service hhs
      WHERE hhs.house_id = h.id AND hhs.service_id = ANY($7::int[])
    ) = cardinality($7::int[])
  )
  AND (
    $8::int IS NULL
    OR EXISTS (
      SELECT 1 FROM house_house_category hhc
      WHERE hhc.house_id = h.id AND hhc.house_category_id = $8
    )
  )
  AND (
    $9::date IS NULL
    OR $10::date IS NULL
    OR NOT EXISTS (
      SELECT 1 FROM request rq
      WHERE rq.house_id = h.id
        AND rq.status IN ('in_progress', 'confirmed')
        AND rq.start_date < $10::date
        AND COALESCE(rq.end_date, rq.start_date + 1) > $9::date
    )
  )
`

type CountHousesFilteredParams struct {
	Query    *string
	City     *string
	PriceMin *int32
	PriceMax *int32
	Rooms    []int32
	RoomsMin *int32
	Services []int32
	Category *int32
	CheckIn  pgtype.Date
	CheckOut pgtype.Date
}

func (q *Queries) CountHousesFiltered(ctx context.Context, arg CountHousesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHousesFiltered,
		arg.Query,
		arg.City,
		arg.PriceMin,
		arg.PriceMax,
		arg.Rooms,
		arg.RoomsMin,
		arg.Services,
		arg.Category,
		arg.CheckIn,
		arg.CheckOut,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHouse = `-- name: CreateHouse :one
INSERT INTO house (
  owner_id, street, house_number, description, price, count_room, number_room,
  area, country, status, deleted, pay, views, lat, lng, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, 'active', false, false, 0,
  $10, $11, now(), now()
)
RETURNING id
`

type CreateHouseParams struct {
	OwnerID     int32
	Street      string
	HouseNumber string
	Description string
	Price       int32
	CountRoom   string
	NumberRoom  *string
	Area        int32
	Country     string
	Lat         *float64
	Lng         *float64
}

// Creates a new listing owned by the given user. New listings are published
// immediately (status='active') for the MVP; the one-time publication fee is a
// front-end stub until YooKassa is wired (then `pay` flips via webhook).
func (q *Queries) CreateHouse(ctx context.Context, arg CreateHouseParams) (int32, error) {
	row := q.db.QueryRow(ctx, createHouse,
		arg.OwnerID,
		arg.Street,
		arg.HouseNumber,
		arg.Description,
		arg.Price,
		arg.CountRoom,
		arg.NumberRoom,
		arg.Area,
		arg.Country,
		arg.Lat,
		arg.Lng,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteHouseCategories = `-- name: DeleteHouseCategories :exec
DELETE FROM house_house_category WHERE house_id = $1
`

func (q *Queries) DeleteHouseCategories(ctx context.Context, houseID int32) error {
	_, err := q.db.Exec(ctx, deleteHouseCategories, houseID)
	return err
}

const deleteHouseServices = `-- name: DeleteHouseServices :exec
DELETE FROM house_house_service WHERE house_id = $1
`

func (q *Queries) DeleteHouseServices(ctx context.Context, houseID int32) error {
	_, err := q.db.Exec(ctx, deleteHouseServices, houseID)
	return err
}

const getHouseByID = `-- name: GetHouseByID :one
SELECT
  h.id,
  h.owner_id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.number_room,
  h.area,
  h.country,
  h.status,
  h.lat,
  h.lng,
  h.views,
  h.created_at,
  h.updated_at,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  ), 0)::float8 AS rating,
  (
    SELECT count(*)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  )::int AS reviews_count
FROM house h
WHERE h.id = $1 AND h.deleted = false
`

type GetHouseByIDRow struct {
	ID           int32
	OwnerID      int32
	Street       string
	HouseNumber  string
	Description  string
	Price        int32
	CountRoom    string
	NumberRoom   *string
	Area         int32
	Country      string
	Status       string
	Lat          *float64
	Lng          *float64
	Views        int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Rating       float64
	ReviewsCount int32
}

func (q *Queries) GetHouseByID(ctx context.Context, id int32) (GetHouseByIDRow, error) {
	row := q.db.QueryRow(ctx, getHouseByID, id)
	var i GetHouseByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Street,
		&i.HouseNumber,
		&i.Description,
		&i.Price,
		&i.CountRoom,
		&i.NumberRoom,
		&i.Area,
		&i.Country,
		&i.Status,
		&i.Lat,
		&i.Lng,
		&i.Views,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Rating,
		&i.ReviewsCount,
	)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name
FROM house_category
WHERE deleted = false
ORDER BY name
`

type ListAllCategoriesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCategoriesRow
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllServices = `-- name: ListAllServices :many
SELECT id, name
FROM service
WHERE deleted = false
ORDER BY name
`

type ListAllServicesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListAllServices(ctx context.Context) ([]ListAllServicesRow, error) {
	rows, err := q.db.Query(ctx, listAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllServicesRow
	for rows.Next() {
		var i ListAllServicesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseCategories = `-- name: ListHouseCategories :many
SELECT c.id, c.name
FROM house_category c
JOIN house_house_category hhc ON hhc.house_category_id = c.id
WHERE hhc.house_id = $1 AND c.deleted = false
ORDER BY c.name
`

type ListHouseCategoriesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListHouseCategories(ctx context.Context, houseID int32) ([]ListHouseCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listHouseCategories, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseCategoriesRow
	for rows.Next() {
		var i ListHouseCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousePhotos = `-- name: ListHousePhotos :many
SELECT id, house_id, path, position
FROM file
WHERE house_id = $1 AND deleted = false
ORDER BY position
`

type ListHousePhotosRow struct {
	ID       int32
	HouseID  *int32
	Path     string
	Position int32
}

func (q *Queries) ListHousePhotos(ctx context.Context, houseID *int32) ([]ListHousePhotosRow, error) {
	rows, err := q.db.Query(ctx, listHousePhotos, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousePhotosRow
	for rows.Next() {
		var i ListHousePhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.Path,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseServices = `-- name: ListHouseServices :many
SELECT s.id, s.name
FROM service s
JOIN house_house_service hhs ON hhs.service_id = s.id
WHERE hhs.house_id = $1 AND s.deleted = false
ORDER BY s.name
`

type ListHouseServicesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListHouseServices(ctx context.Context, houseID int32) ([]ListHouseServicesRow, error) {
	rows, err := q.db.Query(ctx, listHouseServices, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseServicesRow
	for rows.Next() {
		var i ListHouseServicesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousesByOwner = `-- name: ListHousesByOwner :many
SELECT
  h.id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.area,
  h.country,
  h.status,
  h.lat,
  h.lng,
  h.views,
  h.created_at,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  ), 0)::float8 AS rating,
  (
    SELECT count(*)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  )::int AS reviews_count,
  COALESCE((
    SELECT f.path
    FROM file f
    WHERE f.house_id = h.id AND f.deleted = false
    ORDER BY f.position
    LIMIT 1
  ), '')::text AS cover_path
FROM house h
WHERE h.owner_id = $1 AND h.deleted = false
ORDER BY h.created_at DESC
LIMIT $3 OFFSET $2
`

type ListHousesByOwnerParams struct {
	OwnerID      int32
	ResultOffset int32
	ResultLimit  int32
}

type ListHousesByOwnerRow struct {
	ID           int32
	Street       string
	HouseNumber  string
	Description  string
	Price        int32
	CountRoom    string
	Area         int32
	Country      string
	Status       string
	Lat          *float64
	Lng          *float64
	Views        int32
	CreatedAt    pgtype.Timestamp
	Rating       float64
	ReviewsCount int32
	CoverPath    string
}

func (q *Queries) ListHousesByOwner(ctx context.Context, arg ListHousesByOwnerParams) ([]ListHousesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listHousesByOwner, arg.OwnerID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousesByOwnerRow
	for rows.Next() {
		var i ListHousesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Street,
			&i.HouseNumber,
			&i.Description,
			&i.Price,
			&i.CountRoom,
			&i.Area,
			&i.Country,
			&i.Status,
			&i.Lat,
			&i.Lng,
			&i.Views,
			&i.CreatedAt,
			&i.Rating,
			&i.ReviewsCount,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousesFiltered = `-- name: ListHousesFiltered :many
SELECT
  h.id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.area,
  h.country,
  h.status,
  h.lat,
  h.lng,
  h.views,
  h.created_at,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  ), 0)::float8 AS rating,
  (
    SELECT count(*)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  )::int AS reviews_count,
  COALESCE((
    SELECT f.path
    FROM file f
    WHERE f.house_id = h.id AND f.deleted = false
    ORDER BY f.position
    LIMIT 1
  ), '')::text AS cover_path
FROM house h
WHERE h.deleted = false
  AND h.status = 'active'
  AND (
    $1::text IS NULL
    OR h.street ILIKE '%' || $1 || '%'
    OR h.house_number ILIKE '%' || $1 || '%'
    OR h.description ILIKE '%' || $1 || '%'
    OR h.country ILIKE '%' || $1 || '%'
  )
  AND ($2::text IS NULL OR h.country = $2)
  AND ($3::int IS NULL OR h.price >= $3)
  AND ($4::int IS NULL OR h.price <= $4)
  AND (
    (cardinality($5::int[]) = 0 AND $6::int IS NULL)
    OR (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) = ANY($5::int[])
    OR (
      $6::int IS NOT NULL
      AND (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) >= $6
    )
  )
  AND (
    cardinality($7::int[]) = 0
    OR (
      SELECT count(DISTINCT hhs.service_id)
      FROM house_house_service hhs
      WHERE hhs.house_id = h.id AND hhs.service_id = ANY($7::int[])
    ) = cardinality($7::int[])
  )
  AND (
    $8::int IS NULL
    OR EXISTS (
      SELECT 1 FROM house_house_category hhc
      WHERE hhc.house_id = h.id AND hhc.house_category_id = $8
    )
  )
  AND (
    $9::date IS NULL
    OR $10::date IS NULL
    OR NOT EXISTS (
      SELECT 1 FROM request rq
      WHERE rq.house_id = h.id
        AND rq.status IN ('in_progress', 'confirmed')
        AND rq.start_date < $10::date
        AND COALESCE(rq.end_date, rq.start_date + 1) > $9::date
    )
  )
ORDER BY
  CASE WHEN $11::text = 'price_asc' THEN h.price END ASC NULLS LAST,
  CASE WHEN $11::text = 'price_desc' THEN h.price END DESC NULLS LAST,
  CASE WHEN $11::text = 'newest' THEN h.created_at END DESC NULLS LAST,
  h.date_top DESC NULLS LAST,
  h.created_at DESC
LIMIT $13 OFFSET $12
`

type ListHousesFilteredParams struct {
	Query        *string
	City         *string
	PriceMin     *int32
	PriceMax     *int32
	Rooms        []int32
	RoomsMin     *int32
	Services     []int32
	Category     *int32
	CheckIn      pgtype.Date
	CheckOut     pgtype.Date
	Sort         string
	ResultOffset int32
	ResultLimit  int32
}

type ListHousesFilteredRow struct {
	ID           int32
	Street       string
	HouseNumber  string
	Description  string
	Price        int32
	CountRoom    string
	Area         int32
	Country      string
	Status       string
	Lat          *float64
	Lng          *float64
	Views        int32
	CreatedAt    pgtype.Timestamp
	Rating       float64
	ReviewsCount int32
	CoverPath    string
}

func (q *Queries) ListHousesFiltered(ctx context.Context, arg ListHousesFilteredParams) ([]ListHousesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listHousesFiltered,
		arg.Query,
		arg.City,
		arg.PriceMin,
		arg.PriceMax,
		arg.Rooms,
		arg.RoomsMin,
		arg.Services,
		arg.Category,
		arg.CheckIn,
		arg.CheckOut,
		arg.Sort,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousesFilteredRow
	for rows.Next() {
		var i ListHousesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Street,
			&i.HouseNumber,
			&i.Description,
			&i.Price,
			&i.CountRoom,
			&i.Area,
			&i.Country,
			&i.Status,
			&i.Lat,
			&i.Lng,
			&i.Views,
			&i.CreatedAt,
			&i.Rating,
			&i.ReviewsCount,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHouse = `-- name: UpdateHouse :execrows
UPDATE house
SET street = $1,
    house_number = $2,
    description = $3,
    price = $4,
    count_room = $5,
    number_room = $6,
    area = $7,
    country = $8,
    lat = $9,
    lng = $10,
    updated_at = now()
WHERE id = $11 AND owner_id = $12 AND deleted = false
`

type UpdateHouseParams struct {
	Street      string
	HouseNumber string
	Description string
	Price       int32
	CountRoom   string
	NumberRoom  *string
	Area        int32
	Country     string
	Lat         *float64
	Lng         *float64
	ID          int32
	OwnerID     int32
}

// Updates a listing owned by the given user. Returns the number of affected
// rows so the caller can distinguish "not found / not owner" (0) from success.
func (q *Queries) UpdateHouse(ctx context.Context, arg UpdateHouseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateHouse,
		arg.Street,
		arg.HouseNumber,
		arg.Description,
		arg.Price,
		arg.CountRoom,
		arg.NumberRoom,
		arg.Area,
		arg.Country,
		arg.Lat,
		arg.Lng,
		arg.ID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
