// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHouseCategory = `-- name: AddHouseCategory :exec
INSERT INTO house_house_category (house_id, house_category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddHouseCategoryParams struct {
	HouseID         int32
	HouseCategoryID int32
}

func (q *Queries) AddHouseCategory(ctx context.Context, arg AddHouseCategoryParams) error {
	_, err := q.db.Exec(ctx, addHouseCategory, arg.HouseID, arg.HouseCategoryID)
	return err
}

const addHousePhoto = `-- name: AddHousePhoto :exec
INSERT INTO file (house_id, name, size, format, path, deleted, position, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, false, $6, now(), now())
`

type AddHousePhotoParams struct {
	HouseID  *int32
	Name     string
	Size     *int32
	Format   string
	Path     string
	Position int32
}

func (q *Queries) AddHousePhoto(ctx context.Context, arg AddHousePhotoParams) error {
	_, err := q.db.Exec(ctx, addHousePhoto,
		arg.HouseID,
		arg.Name,
		arg.Size,
		arg.Format,
		arg.Path,
		arg.Position,
	)
	return err
}

const addHouseService = `-- name: AddHouseService :exec
INSERT INTO house_house_service (house_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddHouseServiceParams struct {
	HouseID   int32
	ServiceID int32
}

func (q *Queries) AddHouseService(ctx context.Context, arg AddHouseServiceParams) error {
	_, err := q.db.Exec(ctx, addHouseService, arg.HouseID, arg.ServiceID)
	return err
}

const countHousesByOwner = `-- name: CountHousesByOwner :one
SELECT count(*)
FROM house h
WHERE h.owner_id = $1 AND h.deleted = false
`

func (q *Queries) CountHousesByOwner(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countHousesByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHousesFiltered = `-- name: CountHousesFiltered :one
SELECT count(*)
FROM house h
WHERE h.deleted = false
  AND h.status = 'active'
  AND (
    cardinality($1::int[]) = 0
    OR h.id = ANY($1::int[])
  )
  AND (
    $2::text IS NULL
    OR h.street ILIKE '%' || $2 || '%'
    OR h.house_number ILIKE '%' || $2 || '%'
    OR h.description ILIKE '%' || $2 || '%'
    OR h.country ILIKE '%' || $2 || '%'
  )
  AND ($3::text IS NULL OR h.country = $3)
  AND ($4::int IS NULL OR h.price >= $4)
  AND ($5::int IS NULL OR h.price <= $5)
  AND (
    (cardinality($6::int[]) = 0 AND $7::int IS NULL)
    OR (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) = ANY($6::int[])
    OR (
      $7::int IS NOT NULL
      AND (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) >= $7
    )
  )
  AND (
    cardinality($8::int[]) = 0
    OR (
      SELECT count(DISTINCT hhs.service_id)
      FROM house_house_service hhs
      WHERE hhs.house_id = h.id AND hhs.service_id = ANY($8::int[])
    ) = cardinality($8::int[])
  )
  AND (
    $9::int IS NULL
    OR EXISTS (
      SELECT 1 FROM house_house_category hhc
      WHERE hhc.house_id = h.id AND hhc.house_category_id = $9
    )
  )
  AND (
    $10::date IS NULL
    OR $11::date IS NULL
    OR NOT EXISTS (
      SELECT 1 FROM request rq
      WHERE rq.house_id = h.id
        AND rq.status = 'confirmed'
        AND rq.start_date < $11::date
        AND COALESCE(rq.end_date, rq.start_date + 1) > $10::date
    )
  )
  AND (
    $12::int IS NULL
    OR h.max_guests IS NULL
    OR h.max_guests >= $12
  )
  AND ($13::boolean IS NULL OR ($13::boolean = true AND h.pets_allowed IN ('allowed', 'on_request')))
  AND ($14::boolean IS NULL OR ($14::boolean = true AND h.children_allowed IN ('allowed', 'on_request')))
  AND ($15::boolean IS NULL OR ($15::boolean = true AND h.events_allowed IN ('allowed', 'on_request')))
  AND ($16::float8 IS NULL OR h.lat >= $16::float8)
  AND ($17::float8 IS NULL OR h.lat <= $17::float8)
  AND ($18::float8 IS NULL OR h.lng >= $18::float8)
  AND ($19::float8 IS NULL OR h.lng <= $19::float8)
`

type CountHousesFilteredParams struct {
	HouseIds        []int32
	Query           *string
	City            *string
	PriceMin        *int32
	PriceMax        *int32
	Rooms           []int32
	RoomsMin        *int32
	Services        []int32
	Category        *int32
	CheckIn         pgtype.Date
	CheckOut        pgtype.Date
	Guests          *int32
	PetsAllowed     *bool
	ChildrenAllowed *bool
	EventsAllowed   *bool
	MinLat          *float64
	MaxLat          *float64
	MinLng          *float64
	MaxLng          *float64
}

func (q *Queries) CountHousesFiltered(ctx context.Context, arg CountHousesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHousesFiltered,
		arg.HouseIds,
		arg.Query,
		arg.City,
		arg.PriceMin,
		arg.PriceMax,
		arg.Rooms,
		arg.RoomsMin,
		arg.Services,
		arg.Category,
		arg.CheckIn,
		arg.CheckOut,
		arg.Guests,
		arg.PetsAllowed,
		arg.ChildrenAllowed,
		arg.EventsAllowed,
		arg.MinLat,
		arg.MaxLat,
		arg.MinLng,
		arg.MaxLng,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHouse = `-- name: CreateHouse :one
INSERT INTO house (
  owner_id, street, house_number, description, price, count_room, number_room,
  area, country, status, deleted, pay, views, lat, lng, qc_geo, max_guests,
  check_in_after, check_out_before, smoking_allowed, pets_allowed, children_allowed, events_allowed,
  created_at, updated_at, pois
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, 'pending_moderation', false, false, 0,
  $10, $11, $12, $13,
  $14, $15, $16,
  $17, $18, $19,
  now(), now(), $20
)
RETURNING id
`

type CreateHouseParams struct {
	OwnerID         int32
	Street          string
	HouseNumber     string
	Description     string
	Price           int32
	CountRoom       string
	NumberRoom      *string
	Area            int32
	Country         string
	Lat             *float64
	Lng             *float64
	QcGeo           *int32
	MaxGuests       *int32
	CheckInAfter    pgtype.Time
	CheckOutBefore  pgtype.Time
	SmokingAllowed  *string
	PetsAllowed     *string
	ChildrenAllowed *string
	EventsAllowed   *string
	Pois            []byte
}

// Creates a new listing owned by the given user. New listings start in
// 'pending_moderation': the moderation pipeline (prefilter + LLM verdict)
// flips them to 'active' / 'moderation_review' / 'rejected'.
func (q *Queries) CreateHouse(ctx context.Context, arg CreateHouseParams) (int32, error) {
	row := q.db.QueryRow(ctx, createHouse,
		arg.OwnerID,
		arg.Street,
		arg.HouseNumber,
		arg.Description,
		arg.Price,
		arg.CountRoom,
		arg.NumberRoom,
		arg.Area,
		arg.Country,
		arg.Lat,
		arg.Lng,
		arg.QcGeo,
		arg.MaxGuests,
		arg.CheckInAfter,
		arg.CheckOutBefore,
		arg.SmokingAllowed,
		arg.PetsAllowed,
		arg.ChildrenAllowed,
		arg.EventsAllowed,
		arg.Pois,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteHouseCategories = `-- name: DeleteHouseCategories :exec
DELETE FROM house_house_category WHERE house_id = $1
`

func (q *Queries) DeleteHouseCategories(ctx context.Context, houseID int32) error {
	_, err := q.db.Exec(ctx, deleteHouseCategories, houseID)
	return err
}

const deleteHouseServices = `-- name: DeleteHouseServices :exec
DELETE FROM house_house_service WHERE house_id = $1
`

func (q *Queries) DeleteHouseServices(ctx context.Context, houseID int32) error {
	_, err := q.db.Exec(ctx, deleteHouseServices, houseID)
	return err
}

const getHouseByID = `-- name: GetHouseByID :one
SELECT
  h.id,
  h.owner_id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.number_room,
  h.area,
  h.country,
  h.status,
  h.rejection_reason,
  h.max_guests,
  h.lat,
  h.lng,
  h.qc_geo,
  h.views,
  COALESCE((
    SELECT sum(d.authenticated_views + d.guest_views)
    FROM listing_view_daily d
    WHERE d.house_id=h.id
      AND d.view_date >= ((now() AT TIME ZONE 'UTC')::date - 29)
  ), 0)::int AS views_30d,
  h.check_in_after,
  h.check_out_before,
  h.smoking_allowed,
  h.pets_allowed,
  h.children_allowed,
  h.events_allowed,
  h.created_at,
  h.updated_at,
  COALESCE((SELECT array_agg(lp.type ORDER BY lp.type)::text[] FROM listing_promotion lp WHERE lp.house_id=h.id AND lp.status='active' AND lp.starts_at<=now() AND lp.expires_at>now()),ARRAY[]::text[])::text[] AS promotion_types,
  COALESCE((SELECT max(lp.expires_at)::text FROM listing_promotion lp WHERE lp.house_id=h.id AND lp.status='active' AND lp.starts_at<=now() AND lp.expires_at>now()),'')::text AS promotion_expires_at,
  h.reviews_summary,
  h.location_summary,
  COALESCE(h.pois, '[]'::jsonb) AS pois,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  ), 0)::float8 AS rating,
  (
    SELECT count(*)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  )::int AS reviews_count,
  u.name AS owner_name,
  u.surname AS owner_surname,
  u.patronymic AS owner_patronymic,
  u.phone AS owner_phone,
  u.avatar_url AS owner_avatar_url,
  u.is_verified AS owner_is_verified,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    JOIN house owner_h ON owner_h.id = rv.house_id
    WHERE owner_h.owner_id = h.owner_id AND rv.status = 'active'
  ), 0.0)::float8 AS owner_rating,
  COALESCE((
    SELECT count(*)::int
    FROM review rv
    JOIN house owner_h ON owner_h.id = rv.house_id
    WHERE owner_h.owner_id = h.owner_id AND rv.status = 'active'
  ), 0)::int AS owner_reviews_count,
  COALESCE((
    SELECT count(*)::int
    FROM house owner_h
    WHERE owner_h.owner_id = h.owner_id AND owner_h.deleted = false
  ), 0)::int AS owner_listings_count
FROM house h
JOIN "user" u ON h.owner_id = u.id
WHERE h.id = $1 AND h.deleted = false
`

type GetHouseByIDRow struct {
	ID                 int32
	OwnerID            int32
	Street             string
	HouseNumber        string
	Description        string
	Price              int32
	CountRoom          string
	NumberRoom         *string
	Area               int32
	Country            string
	Status             string
	RejectionReason    *string
	MaxGuests          *int32
	Lat                *float64
	Lng                *float64
	QcGeo              *int32
	Views              int32
	Views30d           int32
	CheckInAfter       pgtype.Time
	CheckOutBefore     pgtype.Time
	SmokingAllowed     *string
	PetsAllowed        *string
	ChildrenAllowed    *string
	EventsAllowed      *string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	PromotionTypes     []string
	PromotionExpiresAt string
	ReviewsSummary     *string
	LocationSummary    *string
	Pois               []byte
	Rating             float64
	ReviewsCount       int32
	OwnerName          *string
	OwnerSurname       *string
	OwnerPatronymic    *string
	OwnerPhone         *string
	OwnerAvatarUrl     *string
	OwnerIsVerified    bool
	OwnerRating        float64
	OwnerReviewsCount  int32
	OwnerListingsCount int32
}

func (q *Queries) GetHouseByID(ctx context.Context, id int32) (GetHouseByIDRow, error) {
	row := q.db.QueryRow(ctx, getHouseByID, id)
	var i GetHouseByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Street,
		&i.HouseNumber,
		&i.Description,
		&i.Price,
		&i.CountRoom,
		&i.NumberRoom,
		&i.Area,
		&i.Country,
		&i.Status,
		&i.RejectionReason,
		&i.MaxGuests,
		&i.Lat,
		&i.Lng,
		&i.QcGeo,
		&i.Views,
		&i.Views30d,
		&i.CheckInAfter,
		&i.CheckOutBefore,
		&i.SmokingAllowed,
		&i.PetsAllowed,
		&i.ChildrenAllowed,
		&i.EventsAllowed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromotionTypes,
		&i.PromotionExpiresAt,
		&i.ReviewsSummary,
		&i.LocationSummary,
		&i.Pois,
		&i.Rating,
		&i.ReviewsCount,
		&i.OwnerName,
		&i.OwnerSurname,
		&i.OwnerPatronymic,
		&i.OwnerPhone,
		&i.OwnerAvatarUrl,
		&i.OwnerIsVerified,
		&i.OwnerRating,
		&i.OwnerReviewsCount,
		&i.OwnerListingsCount,
	)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name
FROM house_category
WHERE deleted = false
ORDER BY name
`

type ListAllCategoriesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCategoriesRow
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllServices = `-- name: ListAllServices :many
SELECT id, name
FROM service
WHERE deleted = false
ORDER BY name
`

type ListAllServicesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListAllServices(ctx context.Context) ([]ListAllServicesRow, error) {
	rows, err := q.db.Query(ctx, listAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllServicesRow
	for rows.Next() {
		var i ListAllServicesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseCategories = `-- name: ListHouseCategories :many
SELECT c.id, c.name
FROM house_category c
JOIN house_house_category hhc ON hhc.house_category_id = c.id
WHERE hhc.house_id = $1 AND c.deleted = false
ORDER BY c.name
`

type ListHouseCategoriesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListHouseCategories(ctx context.Context, houseID int32) ([]ListHouseCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listHouseCategories, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseCategoriesRow
	for rows.Next() {
		var i ListHouseCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousePhotos = `-- name: ListHousePhotos :many
SELECT id, house_id, path, position
FROM file
WHERE house_id = $1 AND deleted = false
ORDER BY position
`

type ListHousePhotosRow struct {
	ID       int32
	HouseID  *int32
	Path     string
	Position int32
}

func (q *Queries) ListHousePhotos(ctx context.Context, houseID *int32) ([]ListHousePhotosRow, error) {
	rows, err := q.db.Query(ctx, listHousePhotos, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousePhotosRow
	for rows.Next() {
		var i ListHousePhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.Path,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseServices = `-- name: ListHouseServices :many
SELECT s.id, s.name
FROM service s
JOIN house_house_service hhs ON hhs.service_id = s.id
WHERE hhs.house_id = $1 AND s.deleted = false
ORDER BY s.name
`

type ListHouseServicesRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListHouseServices(ctx context.Context, houseID int32) ([]ListHouseServicesRow, error) {
	rows, err := q.db.Query(ctx, listHouseServices, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseServicesRow
	for rows.Next() {
		var i ListHouseServicesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousesByOwner = `-- name: ListHousesByOwner :many
SELECT
  h.id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.area,
  h.country,
  h.status,
  h.rejection_reason,
  h.max_guests,
  h.lat,
  h.lng,
  h.qc_geo,
  h.views,
  COALESCE((
    SELECT sum(d.authenticated_views + d.guest_views)
    FROM listing_view_daily d
    WHERE d.house_id=h.id
      AND d.view_date >= ((now() AT TIME ZONE 'UTC')::date - 29)
  ), 0)::int AS views_30d,
  h.check_in_after,
  h.check_out_before,
  h.smoking_allowed,
  h.pets_allowed,
  h.children_allowed,
  h.events_allowed,
  h.created_at,
  COALESCE((SELECT array_agg(lp.type ORDER BY lp.type)::text[] FROM listing_promotion lp WHERE lp.house_id=h.id AND lp.status='active' AND lp.starts_at<=now() AND lp.expires_at>now()),ARRAY[]::text[])::text[] AS promotion_types,
  COALESCE((SELECT max(lp.expires_at)::text FROM listing_promotion lp WHERE lp.house_id=h.id AND lp.status='active' AND lp.starts_at<=now() AND lp.expires_at>now()),'')::text AS promotion_expires_at,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  ), 0)::float8 AS rating,
  (
    SELECT count(*)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  )::int AS reviews_count,
  COALESCE((
    SELECT f.path
    FROM file f
    WHERE f.house_id = h.id AND f.deleted = false
    ORDER BY f.position
    LIMIT 1
  ), '')::text AS cover_path
FROM house h
WHERE h.owner_id = $1 AND h.deleted = false
ORDER BY h.created_at DESC
LIMIT $3 OFFSET $2
`

type ListHousesByOwnerParams struct {
	OwnerID      int32
	ResultOffset int32
	ResultLimit  int32
}

type ListHousesByOwnerRow struct {
	ID                 int32
	Street             string
	HouseNumber        string
	Description        string
	Price              int32
	CountRoom          string
	Area               int32
	Country            string
	Status             string
	RejectionReason    *string
	MaxGuests          *int32
	Lat                *float64
	Lng                *float64
	QcGeo              *int32
	Views              int32
	Views30d           int32
	CheckInAfter       pgtype.Time
	CheckOutBefore     pgtype.Time
	SmokingAllowed     *string
	PetsAllowed        *string
	ChildrenAllowed    *string
	EventsAllowed      *string
	CreatedAt          pgtype.Timestamp
	PromotionTypes     []string
	PromotionExpiresAt string
	Rating             float64
	ReviewsCount       int32
	CoverPath          string
}

func (q *Queries) ListHousesByOwner(ctx context.Context, arg ListHousesByOwnerParams) ([]ListHousesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listHousesByOwner, arg.OwnerID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousesByOwnerRow
	for rows.Next() {
		var i ListHousesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Street,
			&i.HouseNumber,
			&i.Description,
			&i.Price,
			&i.CountRoom,
			&i.Area,
			&i.Country,
			&i.Status,
			&i.RejectionReason,
			&i.MaxGuests,
			&i.Lat,
			&i.Lng,
			&i.QcGeo,
			&i.Views,
			&i.Views30d,
			&i.CheckInAfter,
			&i.CheckOutBefore,
			&i.SmokingAllowed,
			&i.PetsAllowed,
			&i.ChildrenAllowed,
			&i.EventsAllowed,
			&i.CreatedAt,
			&i.PromotionTypes,
			&i.PromotionExpiresAt,
			&i.Rating,
			&i.ReviewsCount,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousesFiltered = `-- name: ListHousesFiltered :many
WITH filtered AS MATERIALIZED (
  SELECT h.id, h.owner_id, h.street, h.description, h.price, h.deleted, h.count_room, h.status, h.country, h.created_at, h.updated_at, h.views, h.last_date_view, h.views_current_day, h.date_top, h.pay, h.house_number, h.area, h.number_room, h.rejection_reason, h.lat, h.lng, h.qc_geo, h.max_guests, h.check_in_after, h.check_out_before, h.smoking_allowed, h.pets_allowed, h.children_allowed, h.events_allowed, h.reviews_summary, h.location_summary, h.pois FROM house h
  WHERE h.deleted = false
    AND h.status = 'active'
    AND (cardinality($4::int[]) = 0 OR h.id = ANY($4::int[]))
    AND ($5::text IS NULL OR h.street ILIKE '%' || $5 || '%' OR h.house_number ILIKE '%' || $5 || '%' OR h.description ILIKE '%' || $5 || '%' OR h.country ILIKE '%' || $5 || '%')
    AND ($6::text IS NULL OR h.country = $6)
    AND ($7::int IS NULL OR h.price >= $7)
    AND ($8::int IS NULL OR h.price <= $8)
    AND ((cardinality($9::int[]) = 0 AND $10::int IS NULL) OR (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) = ANY($9::int[]) OR ($10::int IS NOT NULL AND (CASE WHEN h.count_room ~ '^[0-9]+$' THEN h.count_room::int END) >= $10))
    AND (cardinality($11::int[]) = 0 OR (SELECT count(DISTINCT hhs.service_id) FROM house_house_service hhs WHERE hhs.house_id = h.id AND hhs.service_id = ANY($11::int[])) = cardinality($11::int[]))
    AND ($12::int IS NULL OR EXISTS (SELECT 1 FROM house_house_category hhc WHERE hhc.house_id = h.id AND hhc.house_category_id = $12))
    AND ($13::date IS NULL OR $14::date IS NULL OR NOT EXISTS (SELECT 1 FROM request rq WHERE rq.house_id = h.id AND rq.status = 'confirmed' AND rq.start_date < $14::date AND COALESCE(rq.end_date, rq.start_date + 1) > $13::date))
    AND ($15::int IS NULL OR h.max_guests IS NULL OR h.max_guests >= $15)
    AND ($16::boolean IS NULL OR ($16::boolean = true AND h.pets_allowed IN ('allowed', 'on_request')))
    AND ($17::boolean IS NULL OR ($17::boolean = true AND h.children_allowed IN ('allowed', 'on_request')))
    AND ($18::boolean IS NULL OR ($18::boolean = true AND h.events_allowed IN ('allowed', 'on_request')))
    AND ($19::float8 IS NULL OR h.lat >= $19::float8)
    AND ($20::float8 IS NULL OR h.lat <= $20::float8)
    AND ($21::float8 IS NULL OR h.lng >= $21::float8)
    AND ($22::float8 IS NULL OR h.lng <= $22::float8)
), promoted AS (
  SELECT f.id AS house_id, lp.activated_at
  FROM filtered f JOIN listing_promotion lp ON lp.house_id=f.id
  WHERE lp.type='boost' AND lp.status='active' AND lp.starts_at<=now() AND lp.expires_at>now()
  ORDER BY lp.activated_at DESC,lp.id
  LIMIT 2
), popularity AS (
  SELECT d.house_id,
         sum(CASE WHEN d.is_anomalous THEN LEAST(d.authenticated_views, 10) ELSE d.authenticated_views END)::bigint AS score
  FROM listing_view_daily d
  JOIN filtered f ON f.id=d.house_id
  WHERE $1::text='popular'
    AND d.view_date >= ((now() AT TIME ZONE 'UTC')::date - 30)
    AND d.view_date < (now() AT TIME ZONE 'UTC')::date
  GROUP BY d.house_id
)
SELECT
  h.id,
  h.owner_id,
  h.street,
  h.house_number,
  h.description,
  h.price,
  h.count_room,
  h.area,
  h.country,
  h.status,
  h.max_guests,
  h.lat,
  h.lng,
  h.qc_geo,
  h.views,
  h.check_in_after,
  h.check_out_before,
  h.smoking_allowed,
  h.pets_allowed,
  h.children_allowed,
  h.events_allowed,
  h.created_at,
  COALESCE(promo.promotion_types,ARRAY[]::text[])::text[] AS promotion_types,
  COALESCE(promo.promotion_expires_at::text,'')::text AS promotion_expires_at,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  ), 0)::float8 AS rating,
  (
    SELECT count(*)
    FROM review rv
    WHERE rv.house_id = h.id AND rv.status = 'active'
  )::int AS reviews_count,
  COALESCE((
    SELECT f.path
    FROM file f
    WHERE f.house_id = h.id AND f.deleted = false
    ORDER BY f.position
    LIMIT 1
  ), '')::text AS cover_path
FROM filtered h
LEFT JOIN promoted top_promo ON top_promo.house_id=h.id
LEFT JOIN popularity pop ON pop.house_id=h.id
LEFT JOIN LATERAL (
 SELECT array_agg(lp.type ORDER BY lp.type)::text[] AS promotion_types,max(lp.expires_at) AS promotion_expires_at
 FROM listing_promotion lp WHERE lp.house_id=h.id AND lp.status='active' AND lp.starts_at<=now() AND lp.expires_at>now()
) promo ON true
ORDER BY
  CASE WHEN $1::text IN ('', 'newest', 'oldest', 'popular') THEN CASE WHEN top_promo.house_id IS NOT NULL THEN 0 ELSE 1 END ELSE 0 END,
  CASE WHEN $1::text = 'price_asc' THEN h.price END ASC NULLS LAST,
  CASE WHEN $1::text = 'price_desc' THEN h.price END DESC NULLS LAST,
  CASE WHEN $1::text = 'oldest' THEN h.created_at END ASC NULLS LAST,
  CASE WHEN $1::text = 'popular' THEN COALESCE(pop.score, 0) END DESC NULLS LAST,
  CASE WHEN $1::text IN ('', 'newest', 'popular', 'price_asc', 'price_desc') THEN h.created_at END DESC NULLS LAST,
  CASE WHEN $1::text = 'oldest' THEN h.id END ASC NULLS LAST,
  h.id DESC
LIMIT $3 OFFSET $2
`

type ListHousesFilteredParams struct {
	Sort            string
	ResultOffset    int32
	ResultLimit     int32
	HouseIds        []int32
	Query           *string
	City            *string
	PriceMin        *int32
	PriceMax        *int32
	Rooms           []int32
	RoomsMin        *int32
	Services        []int32
	Category        *int32
	CheckIn         pgtype.Date
	CheckOut        pgtype.Date
	Guests          *int32
	PetsAllowed     *bool
	ChildrenAllowed *bool
	EventsAllowed   *bool
	MinLat          *float64
	MaxLat          *float64
	MinLng          *float64
	MaxLng          *float64
}

type ListHousesFilteredRow struct {
	ID                 int32
	OwnerID            int32
	Street             string
	HouseNumber        string
	Description        string
	Price              int32
	CountRoom          string
	Area               int32
	Country            string
	Status             string
	MaxGuests          *int32
	Lat                *float64
	Lng                *float64
	QcGeo              *int32
	Views              int32
	CheckInAfter       pgtype.Time
	CheckOutBefore     pgtype.Time
	SmokingAllowed     *string
	PetsAllowed        *string
	ChildrenAllowed    *string
	EventsAllowed      *string
	CreatedAt          pgtype.Timestamp
	PromotionTypes     []string
	PromotionExpiresAt string
	Rating             float64
	ReviewsCount       int32
	CoverPath          string
}

func (q *Queries) ListHousesFiltered(ctx context.Context, arg ListHousesFilteredParams) ([]ListHousesFilteredRow, error) {
	rows, err := q.db.Query(ctx, listHousesFiltered,
		arg.Sort,
		arg.ResultOffset,
		arg.ResultLimit,
		arg.HouseIds,
		arg.Query,
		arg.City,
		arg.PriceMin,
		arg.PriceMax,
		arg.Rooms,
		arg.RoomsMin,
		arg.Services,
		arg.Category,
		arg.CheckIn,
		arg.CheckOut,
		arg.Guests,
		arg.PetsAllowed,
		arg.ChildrenAllowed,
		arg.EventsAllowed,
		arg.MinLat,
		arg.MaxLat,
		arg.MinLng,
		arg.MaxLng,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousesFilteredRow
	for rows.Next() {
		var i ListHousesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Street,
			&i.HouseNumber,
			&i.Description,
			&i.Price,
			&i.CountRoom,
			&i.Area,
			&i.Country,
			&i.Status,
			&i.MaxGuests,
			&i.Lat,
			&i.Lng,
			&i.QcGeo,
			&i.Views,
			&i.CheckInAfter,
			&i.CheckOutBefore,
			&i.SmokingAllowed,
			&i.PetsAllowed,
			&i.ChildrenAllowed,
			&i.EventsAllowed,
			&i.CreatedAt,
			&i.PromotionTypes,
			&i.PromotionExpiresAt,
			&i.Rating,
			&i.ReviewsCount,
			&i.CoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapClusters = `-- name: ListMapClusters :many
SELECT btrim(h.country)::text AS city,
       avg(h.lat)::double precision AS lat,
       avg(h.lng)::double precision AS lng,
       count(*)::integer AS listing_count
FROM house h
WHERE h.status = 'active'
  AND h.deleted = false
  AND h.lat IS NOT NULL
  AND h.lng IS NOT NULL
  AND btrim(h.country) <> ''
GROUP BY btrim(h.country)
ORDER BY listing_count DESC, city
`

type ListMapClustersRow struct {
	City         string
	Lat          float64
	Lng          float64
	ListingCount int32
}

func (q *Queries) ListMapClusters(ctx context.Context) ([]ListMapClustersRow, error) {
	rows, err := q.db.Query(ctx, listMapClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapClustersRow
	for rows.Next() {
		var i ListMapClustersRow
		if err := rows.Scan(
			&i.City,
			&i.Lat,
			&i.Lng,
			&i.ListingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteHousePhotos = `-- name: SoftDeleteHousePhotos :exec
UPDATE file SET deleted = true, updated_at = now() WHERE house_id = $1
`

func (q *Queries) SoftDeleteHousePhotos(ctx context.Context, houseID *int32) error {
	_, err := q.db.Exec(ctx, softDeleteHousePhotos, houseID)
	return err
}

const updateHouse = `-- name: UpdateHouse :execrows
UPDATE house
SET street = $1,
    house_number = $2,
    description = $3,
    price = $4,
    count_room = $5,
    number_room = $6,
    area = $7,
    country = $8,
    lat = $9,
    lng = $10,
    qc_geo = $11,
    max_guests = $12,
    check_in_after = $13,
    check_out_before = $14,
    smoking_allowed = $15,
    pets_allowed = $16,
    children_allowed = $17,
    events_allowed = $18,
    updated_at = now(),
    pois = $19
WHERE id = $20 AND owner_id = $21 AND deleted = false
`

type UpdateHouseParams struct {
	Street          string
	HouseNumber     string
	Description     string
	Price           int32
	CountRoom       string
	NumberRoom      *string
	Area            int32
	Country         string
	Lat             *float64
	Lng             *float64
	QcGeo           *int32
	MaxGuests       *int32
	CheckInAfter    pgtype.Time
	CheckOutBefore  pgtype.Time
	SmokingAllowed  *string
	PetsAllowed     *string
	ChildrenAllowed *string
	EventsAllowed   *string
	Pois            []byte
	ID              int32
	OwnerID         int32
}

// Updates a listing owned by the given user. Returns the number of affected
// rows so the caller can distinguish "not found / not owner" (0) from success.
func (q *Queries) UpdateHouse(ctx context.Context, arg UpdateHouseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateHouse,
		arg.Street,
		arg.HouseNumber,
		arg.Description,
		arg.Price,
		arg.CountRoom,
		arg.NumberRoom,
		arg.Area,
		arg.Country,
		arg.Lat,
		arg.Lng,
		arg.QcGeo,
		arg.MaxGuests,
		arg.CheckInAfter,
		arg.CheckOutBefore,
		arg.SmokingAllowed,
		arg.PetsAllowed,
		arg.ChildrenAllowed,
		arg.EventsAllowed,
		arg.Pois,
		arg.ID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateHouseLocationSummary = `-- name: UpdateHouseLocationSummary :exec
UPDATE house
SET location_summary = $2
WHERE id = $1
`

type UpdateHouseLocationSummaryParams struct {
	ID              int32
	LocationSummary *string
}

func (q *Queries) UpdateHouseLocationSummary(ctx context.Context, arg UpdateHouseLocationSummaryParams) error {
	_, err := q.db.Exec(ctx, updateHouseLocationSummary, arg.ID, arg.LocationSummary)
	return err
}

const updateHouseReviewsSummary = `-- name: UpdateHouseReviewsSummary :exec
UPDATE house
SET reviews_summary = $2
WHERE id = $1
`

type UpdateHouseReviewsSummaryParams struct {
	ID             int32
	ReviewsSummary *string
}

func (q *Queries) UpdateHouseReviewsSummary(ctx context.Context, arg UpdateHouseReviewsSummaryParams) error {
	_, err := q.db.Exec(ctx, updateHouseReviewsSummary, arg.ID, arg.ReviewsSummary)
	return err
}

const userHasConfirmedBookingForHouse = `-- name: UserHasConfirmedBookingForHouse :one
SELECT EXISTS (
  SELECT 1 FROM request
  WHERE user_id = $1 AND house_id = $2
    AND status IN ('confirmed', 'active')
)::boolean
`

type UserHasConfirmedBookingForHouseParams struct {
	UserID  *int32
	HouseID *int32
}

// Returns true if the given user has a confirmed or active booking for the house.
// Used by the detail endpoint to decide whether to reveal exact coordinates.
func (q *Queries) UserHasConfirmedBookingForHouse(ctx context.Context, arg UserHasConfirmedBookingForHouseParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasConfirmedBookingForHouse, arg.UserID, arg.HouseID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
