// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminStory struct {
	ID         int32
	AdminID    int32
	CategoryID *int32
	ServiceID  *int32
	ChangeDate pgtype.Timestamp
	Type       string
	UserID     *int32
}

type Code struct {
	ID    int32
	Email string
	Code  string
	Date  pgtype.Timestamp
}

type Comment struct {
	ID          int32
	OwnerID     int32
	HouseID     int32
	ParentID    *int32
	AddresseeID *int32
	Body        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Conversation struct {
	ID        int64
	HouseID   *int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type ConversationParticipant struct {
	ConversationID int64
	UserID         int32
	LastReadAt     pgtype.Timestamp
}

type DeviceToken struct {
	ID        int64
	UserID    int32
	Token     string
	Platform  string
	Provider  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type DoctrineMigrationVersion struct {
	Version       string
	ExecutedAt    pgtype.Timestamp
	ExecutionTime *int32
}

type EmailLoginCode struct {
	Email     string
	CodeHash  string
	ExpiresAt pgtype.Timestamp
	Attempts  int32
	CreatedAt pgtype.Timestamp
}

type Favorite struct {
	ID        int64
	UserID    int32
	HouseID   int32
	CreatedAt pgtype.Timestamp
}

type File struct {
	ID        int32
	HouseID   *int32
	Name      string
	Size      *int32
	Format    string
	Dir       *string
	Path      string
	Deleted   bool
	Position  int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Guest struct {
	ID      int32
	GuestID int32
}

type House struct {
	ID              int32
	OwnerID         int32
	Street          string
	Description     string
	Price           int32
	Deleted         bool
	CountRoom       string
	Status          string
	Country         string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Views           int32
	LastDateView    pgtype.Timestamp
	ViewsCurrentDay *int32
	DateTop         pgtype.Timestamp
	Pay             bool
	HouseNumber     string
	Area            int32
	NumberRoom      *string
	RejectionReason *string
	Lat             *float64
	Lng             *float64
	MaxGuests       *int32
}

type HouseCategory struct {
	ID        int32
	Name      string
	Deleted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type HouseHouseCategory struct {
	HouseID         int32
	HouseCategoryID int32
}

type HouseHouseService struct {
	HouseID   int32
	ServiceID int32
}

type Message struct {
	ID             int64
	ConversationID int64
	SenderID       int32
	Body           string
	CreatedAt      pgtype.Timestamp
}

type Payment struct {
	ID                int64
	RequestID         *int32
	UserID            *int32
	Provider          string
	ProviderPaymentID *string
	AmountKopecks     int32
	Currency          string
	Status            string
	ConfirmationUrl   *string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	PaidAt            pgtype.Timestamp
}

type RefreshToken struct {
	ID        int64
	UserID    int32
	TokenHash string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
}

type Request struct {
	ID              int32
	HouseID         *int32
	UserID          *int32
	Name            string
	Surname         string
	Lastname        string
	Count           int32
	Message         *string
	Phone           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ConfirmedAt     pgtype.Timestamp
	RejectionReason *string
	GuestID         *string
	Email           *string
}

type RequestViewer struct {
	ID        int32
	RequestID int32
	UserID    *int32
	GuestID   *string
}

type Review struct {
	ID              int32
	OwnerID         int32
	HouseID         int32
	Body            string
	Rating          int32
	Status          string
	RejectionReason *string
	CreatedAt       pgtype.Timestamp
}

type Service struct {
	ID        int32
	Name      string
	Deleted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type SessionIpAddress struct {
	ID   int32
	Uid  string
	City string
}

type User struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           string
	Password        *string
	Roles           []byte
	Deleted         bool
	IsVerified      bool
	GoogleID        *string
	Phone           *string
	Locale          *string
	City            *string
	Enable          bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Code            *string
	DateCode        pgtype.Timestamp
	RejectionReason *string
	VkID            *string
	AvatarUrl       *string
	Birthday        pgtype.Date
}

type View struct {
	ID       int32
	Value    *int64
	ViewDate pgtype.Timestamp
}
