// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminStory struct {
	ID         int32
	AdminID    int32
	CategoryID *int32
	ServiceID  *int32
	ChangeDate pgtype.Timestamp
	Type       string
	UserID     *int32
}

type AuthCode struct {
	Channel          string
	Target           string
	CodeHash         string
	ExpiresAt        pgtype.Timestamptz
	Attempts         int32
	CreatedAt        pgtype.Timestamptz
	DeliveryProvider *string
	DeliveryID       *string
	DeliveryCost     *string
}

type Code struct {
	ID    int32
	Email string
	Code  string
	Date  pgtype.Timestamp
}

type Comment struct {
	ID          int32
	OwnerID     int32
	HouseID     int32
	ParentID    *int32
	AddresseeID *int32
	Body        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Conversation struct {
	ID        int64
	HouseID   *int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ConversationParticipant struct {
	ConversationID    int64
	UserID            int32
	LastReadAt        pgtype.Timestamptz
	LastReadMessageID *int64
}

type DeviceToken struct {
	ID        int64
	UserID    int32
	Token     string
	Platform  string
	Provider  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type DoctrineMigrationVersion struct {
	Version       string
	ExecutedAt    pgtype.Timestamp
	ExecutionTime *int32
}

type EmailOutbox struct {
	ID            int64
	DedupKey      *string
	UserID        *int32
	Recipient     string
	EventType     string
	Subject       string
	BodyText      *string
	BodyHtml      *string
	Status        string
	Attempts      int32
	LastError     *string
	NextAttemptAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
}

type EmailPreference struct {
	UserID     int32
	Booking    bool
	ChatDigest bool
	Reviews    bool
	UpdatedAt  pgtype.Timestamptz
}

type Favorite struct {
	ID        int64
	UserID    int32
	HouseID   int32
	CreatedAt pgtype.Timestamp
}

type File struct {
	ID        int32
	HouseID   *int32
	Name      string
	Size      *int32
	Format    string
	Dir       *string
	Path      string
	Deleted   bool
	Position  int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Guest struct {
	ID      int32
	GuestID int32
}

type House struct {
	ID              int32
	OwnerID         int32
	Street          string
	Description     string
	Price           int32
	Deleted         bool
	CountRoom       string
	Status          string
	Country         string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Views           int32
	LastDateView    pgtype.Timestamp
	ViewsCurrentDay *int32
	DateTop         pgtype.Timestamp
	Pay             bool
	HouseNumber     string
	Area            int32
	NumberRoom      *string
	RejectionReason *string
	Lat             *float64
	Lng             *float64
	MaxGuests       *int32
	CheckInAfter    pgtype.Time
	CheckOutBefore  pgtype.Time
	SmokingAllowed  *string
	PetsAllowed     *string
	ChildrenAllowed *string
	EventsAllowed   *string
	ReviewsSummary  *string
	LocationSummary *string
	Pois            []byte
	QcGeo           *int32
}

type HouseCategory struct {
	ID        int32
	Name      string
	Deleted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type HouseHouseCategory struct {
	HouseID         int32
	HouseCategoryID int32
}

type HouseHouseService struct {
	HouseID   int32
	ServiceID int32
}

type ListingPromotion struct {
	ID               int64
	HouseID          int32
	PurchasedBy      *int32
	PaymentID        *int64
	Type             string
	Status           string
	DurationSeconds  int32
	RemainingSeconds int32
	StartsAt         pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	ActivatedAt      pgtype.Timestamptz
	PausedAt         pgtype.Timestamptz
	PauseReason      *string
	CheckoutKey      pgtype.UUID
	Version          int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ListingViewDaily struct {
	HouseID            int32
	ViewDate           pgtype.Date
	AuthenticatedViews int32
	GuestViews         int32
	IsAnomalous        bool
	UpdatedAt          pgtype.Timestamptz
}

type ListingViewEvent struct {
	EventID    pgtype.UUID
	HouseID    int32
	ViewerHash []byte
	ViewerKind string
	ViewedOn   pgtype.Date
	CreatedAt  pgtype.Timestamptz
	UserID     *int32
}

type LocationSummaryJob struct {
	ID            int64
	HouseID       int32
	City          string
	Street        string
	Pois          []byte
	Status        string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Lat           *float64
	Lng           *float64
	Revision      int64
}

type Message struct {
	ID             int64
	ConversationID int64
	SenderID       *int32
	Body           *string
	CreatedAt      pgtype.Timestamptz
	Kind           string
	Payload        []byte
}

type MessageAttachment struct {
	ID        int64
	MessageID int64
	Url       string
	FileName  *string
	MimeType  *string
	SizeBytes *int64
	Width     *int32
	Height    *int32
	CreatedAt pgtype.Timestamptz
}

type ModerationVerdict struct {
	ID            int64
	HouseID       int32
	ContentHash   string
	Source        string
	Decision      *string
	Category      *string
	Reason        *string
	Confidence    *float32
	RawResponse   []byte
	ModeratorID   *int32
	Status        string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LastError     *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Payment struct {
	ID                    int64
	RequestID             *int32
	UserID                *int32
	Provider              string
	ProviderPaymentID     *string
	AmountKopecks         int32
	Currency              string
	Status                string
	ConfirmationUrl       *string
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
	PaidAt                pgtype.Timestamp
	Purpose               string
	ProductCode           *string
	IdempotencyKey        pgtype.UUID
	Description           *string
	Metadata              []byte
	CanceledAt            pgtype.Timestamptz
	RefundedAmountKopecks int32
	BusinessRefType       *string
	BusinessRefID         *int64
}

type PaymentProduct struct {
	Code            string
	Title           string
	Purpose         string
	AmountKopecks   int32
	Currency        string
	VatCode         int16
	PaymentSubject  string
	PaymentMode     string
	Enabled         bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ServiceType     *string
	DurationSeconds *int32
}

type PaymentReceipt struct {
	ID                    int64
	PaymentID             int64
	RefundID              *int64
	Operation             string
	ProviderReceiptID     *string
	Status                string
	CustomerContactMasked *string
	Payload               []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RegisteredAt          pgtype.Timestamptz
}

type PaymentRefund struct {
	ID               int64
	PaymentID        int64
	ProviderRefundID *string
	IdempotencyKey   pgtype.UUID
	AmountKopecks    int32
	Currency         string
	Status           string
	Reason           string
	InitiatedBy      *int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	SucceededAt      pgtype.Timestamptz
	CanceledAt       pgtype.Timestamptz
}

type PaymentWebhookEvent struct {
	ID               int64
	Provider         string
	EventType        string
	ProviderObjectID string
	DedupKey         string
	Payload          []byte
	Status           string
	Attempts         int32
	NextAttemptAt    pgtype.Timestamptz
	LastError        *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ProcessedAt      pgtype.Timestamptz
}

type PersonalDataRevocation struct {
	ID        int32
	UserID    int32
	RevokedAt pgtype.Timestamp
	EmailHash string
}

type PhoneAuthChallenge struct {
	ID              pgtype.UUID
	PhoneNormalized string
	Purpose         string
	UserID          *int32
	CodeHash        *string
	CodeLength      int32
	Status          string
	DeliveryMode    string
	PendingUntil    pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	Attempts        int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PhoneAuthDelivery struct {
	ID                 int64
	ChallengeID        pgtype.UUID
	Provider           string
	Mode               string
	IdempotencyID      pgtype.UUID
	ProviderDeliveryID *string
	Status             string
	ErrorCode          *string
	ErrorMessage       *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type PhotoHash struct {
	ID        int64
	HouseID   int32
	MediaKey  string
	Phash     int64
	CreatedAt pgtype.Timestamptz
}

type PromotionExpiryJob struct {
	PromotionID int64
	Version     int64
	DueAt       pgtype.Timestamptz
	Status      string
	Attempts    int32
	LastError   *string
	UpdatedAt   pgtype.Timestamptz
}

type RefreshToken struct {
	ID           int64
	UserID       int32
	TokenHash    string
	ExpiresAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	RevokedAt    pgtype.Timestamp
	DeviceName   *string
	DeviceOs     *string
	AppVersion   *string
	IpAddress    *string
	Location     *string
	LastActiveAt pgtype.Timestamp
}

type Request struct {
	ID              int32
	HouseID         *int32
	UserID          *int32
	Name            string
	Surname         string
	Lastname        string
	Count           int32
	Message         *string
	Phone           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ConfirmedAt     pgtype.Timestamp
	RejectionReason *string
	GuestID         *string
	Email           *string
	PhoneNormalized *string
}

type RequestViewer struct {
	ID        int32
	RequestID int32
	UserID    *int32
	GuestID   *string
}

type Review struct {
	ID              int32
	OwnerID         int32
	HouseID         int32
	Body            string
	Rating          int32
	Status          string
	RejectionReason *string
	CreatedAt       pgtype.Timestamp
	RequestID       *int32
	OriginalBody    *string
	PublishedBody   *string
	ContentHash     *string
	ModeratedAt     pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EditAttempts    int32
}

type ReviewModerationJob struct {
	ID                 int64
	TargetType         string
	TargetID           int64
	ContentHash        string
	DetectedCategories []byte
	MaskedBody         *string
	Status             string
	Attempts           int32
	NextAttemptAt      pgtype.Timestamptz
	Decision           *string
	Category           *string
	Reason             *string
	Confidence         *float32
	RawResponse        []byte
	LastError          *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ReviewReply struct {
	ID              int64
	ReviewID        int32
	OwnerID         int32
	OriginalBody    string
	PublishedBody   *string
	Status          string
	ContentHash     string
	RejectionReason *string
	ModeratedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EditAttempts    int32
}

type ReviewSummaryJob struct {
	HouseID    int32
	DirtySince pgtype.Timestamptz
	RunAfter   pgtype.Timestamptz
	Status     string
	Attempts   int32
	LastError  *string
	UpdatedAt  pgtype.Timestamptz
}

type Service struct {
	ID        int32
	Name      string
	Deleted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type SessionIpAddress struct {
	ID   int32
	Uid  string
	City string
}

type User struct {
	ID              int32
	Name            *string
	Surname         *string
	Patronymic      *string
	Email           *string
	Password        *string
	Roles           []byte
	Deleted         bool
	IsVerified      bool
	GoogleID        *string
	Phone           *string
	Locale          *string
	City            *string
	Enable          bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Code            *string
	DateCode        pgtype.Timestamp
	RejectionReason *string
	VkID            *string
	AvatarUrl       *string
	Birthday        pgtype.Date
	PhoneNormalized *string
	PhoneVerifiedAt pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
}

type UserActivityEvent struct {
	ID        int64
	EventKey  string
	UserID    int32
	Scope     string
	EventType string
	EntityID  *int64
	Action    string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	SeenAt    pgtype.Timestamptz
}

type View struct {
	ID       int32
	Value    *int64
	ViewDate pgtype.Timestamp
}
