// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	CancelRequest(ctx context.Context, id int32) (CancelRequestRow, error)
	ConfirmRequest(ctx context.Context, id int32) (ConfirmRequestRow, error)
	CountFavoriteHouses(ctx context.Context, userID int32) (int64, error)
	CountHousesFiltered(ctx context.Context, arg CountHousesFilteredParams) (int64, error)
	CountRequestsByUser(ctx context.Context, arg CountRequestsByUserParams) (int64, error)
	CountRequestsForOwner(ctx context.Context, ownerID int32) (int64, error)
	CountReviewsByHouse(ctx context.Context, houseID int32) (int64, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateRequest(ctx context.Context, arg CreateRequestParams) (CreateRequestRow, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteEmailLoginCode(ctx context.Context, email string) error
	GetEmailLoginCode(ctx context.Context, email string) (EmailLoginCode, error)
	GetHouseByID(ctx context.Context, id int32) (GetHouseByIDRow, error)
	GetHouseForBooking(ctx context.Context, id int32) (GetHouseForBookingRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRequestByID(ctx context.Context, id int32) (GetRequestByIDRow, error)
	GetReviewByID(ctx context.Context, id int32) (GetReviewByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	HouseExists(ctx context.Context, id int32) (bool, error)
	IncrementEmailLoginCodeAttempts(ctx context.Context, email string) error
	ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error)
	ListAllServices(ctx context.Context) ([]ListAllServicesRow, error)
	ListFavoriteHouses(ctx context.Context, arg ListFavoriteHousesParams) ([]ListFavoriteHousesRow, error)
	ListFavoriteIDs(ctx context.Context, userID int32) ([]int32, error)
	ListHouseCategories(ctx context.Context, houseID int32) ([]ListHouseCategoriesRow, error)
	ListHousePhotos(ctx context.Context, houseID *int32) ([]ListHousePhotosRow, error)
	ListHouseServices(ctx context.Context, houseID int32) ([]ListHouseServicesRow, error)
	ListHousesFiltered(ctx context.Context, arg ListHousesFilteredParams) ([]ListHousesFilteredRow, error)
	ListRequestsByUser(ctx context.Context, arg ListRequestsByUserParams) ([]ListRequestsByUserRow, error)
	ListRequestsForOwner(ctx context.Context, arg ListRequestsForOwnerParams) ([]ListRequestsForOwnerRow, error)
	ListReviewsByHouse(ctx context.Context, arg ListReviewsByHouseParams) ([]ListReviewsByHouseRow, error)
	RejectRequest(ctx context.Context, arg RejectRequestParams) (RejectRequestRow, error)
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	ReviewSummaryByHouse(ctx context.Context, houseID int32) (ReviewSummaryByHouseRow, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	UpsertEmailLoginCode(ctx context.Context, arg UpsertEmailLoginCodeParams) error
}

var _ Querier = (*Queries)(nil)
