// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRequest = `-- name: CancelRequest :one
UPDATE request
SET status = 'cancelled', updated_at = now()
WHERE id = $1
RETURNING
  id, COALESCE(house_id, 0)::int AS house_id, COALESCE(user_id, 0)::int AS user_id,
  COALESCE(guest_id, '')::text AS guest_id, COALESCE(email, '')::text AS email,
  name, surname, lastname, count, message, phone, start_date, end_date, status,
  created_at, updated_at, confirmed_at, rejection_reason
`

type CancelRequestRow struct {
	ID              int32
	HouseID         int32
	UserID          int32
	GuestID         string
	Email           string
	Name            string
	Surname         string
	Lastname        string
	Count           int32
	Message         *string
	Phone           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ConfirmedAt     pgtype.Timestamp
	RejectionReason *string
}

func (q *Queries) CancelRequest(ctx context.Context, id int32) (CancelRequestRow, error) {
	row := q.db.QueryRow(ctx, cancelRequest, id)
	var i CancelRequestRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.UserID,
		&i.GuestID,
		&i.Email,
		&i.Name,
		&i.Surname,
		&i.Lastname,
		&i.Count,
		&i.Message,
		&i.Phone,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
		&i.RejectionReason,
	)
	return i, err
}

const confirmRequest = `-- name: ConfirmRequest :one
UPDATE request
SET status = 'confirmed', confirmed_at = now(), updated_at = now()
WHERE id = $1 AND status = 'in_progress'
RETURNING
  id, COALESCE(house_id, 0)::int AS house_id, COALESCE(user_id, 0)::int AS user_id,
  COALESCE(guest_id, '')::text AS guest_id, COALESCE(email, '')::text AS email,
  name, surname, lastname, count, message, phone, start_date, end_date, status,
  created_at, updated_at, confirmed_at, rejection_reason
`

type ConfirmRequestRow struct {
	ID              int32
	HouseID         int32
	UserID          int32
	GuestID         string
	Email           string
	Name            string
	Surname         string
	Lastname        string
	Count           int32
	Message         *string
	Phone           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ConfirmedAt     pgtype.Timestamp
	RejectionReason *string
}

func (q *Queries) ConfirmRequest(ctx context.Context, id int32) (ConfirmRequestRow, error) {
	row := q.db.QueryRow(ctx, confirmRequest, id)
	var i ConfirmRequestRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.UserID,
		&i.GuestID,
		&i.Email,
		&i.Name,
		&i.Surname,
		&i.Lastname,
		&i.Count,
		&i.Message,
		&i.Phone,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
		&i.RejectionReason,
	)
	return i, err
}

const countRequestsByGuest = `-- name: CountRequestsByGuest :one
SELECT count(*) FROM request r
WHERE r.guest_id = $1::text
  AND (
    $2::text = 'all'
    OR ($2::text = 'active' AND (
      r.status = 'in_progress'
      OR r.status = 'pending_verification'
      OR (r.status = 'confirmed' AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE))
    ))
    OR ($2::text = 'history' AND (
      r.status = 'cancelled'
      OR (r.status = 'confirmed' AND r.end_date IS NOT NULL AND r.end_date < CURRENT_DATE)
    ))
  )
`

type CountRequestsByGuestParams struct {
	GuestID string
	Scope   string
}

func (q *Queries) CountRequestsByGuest(ctx context.Context, arg CountRequestsByGuestParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByGuest, arg.GuestID, arg.Scope)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByUser = `-- name: CountRequestsByUser :one
SELECT count(*) FROM request r
WHERE r.user_id = $1::int
  AND (
    $2::text = 'all'
    OR ($2::text = 'active' AND (
      r.status = 'in_progress'
      OR (r.status = 'confirmed' AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE))
    ))
    OR ($2::text = 'history' AND (
      r.status = 'cancelled'
      OR (r.status = 'confirmed' AND r.end_date IS NOT NULL AND r.end_date < CURRENT_DATE)
    ))
  )
`

type CountRequestsByUserParams struct {
	UserID int32
	Scope  string
}

func (q *Queries) CountRequestsByUser(ctx context.Context, arg CountRequestsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByUser, arg.UserID, arg.Scope)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsForOwner = `-- name: CountRequestsForOwner :one
SELECT count(*)
FROM request r
JOIN house h ON h.id = r.house_id
WHERE h.owner_id = $1
  AND r.status != 'pending_verification'
`

func (q *Queries) CountRequestsForOwner(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsForOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO request (
  house_id, user_id, guest_id, email, name, surname, lastname, count, message, phone,
  start_date, end_date, status, created_at, updated_at
)
VALUES (
  $1::int, $2, $3, LOWER(TRIM($4)),
  $5, $6, $7, $8::int,
  $9, $10, $11, $12,
  $13::text, now(), now()
)
RETURNING
  id, COALESCE(house_id, 0)::int AS house_id, COALESCE(user_id, 0)::int AS user_id,
  COALESCE(guest_id, '')::text AS guest_id, COALESCE(email, '')::text AS email,
  name, surname, lastname, count, message, phone, start_date, end_date, status,
  created_at, updated_at, confirmed_at, rejection_reason
`

type CreateRequestParams struct {
	HouseID   int32
	UserID    *int32
	GuestID   *string
	Email     *string
	Name      string
	Surname   string
	Lastname  string
	Count     int32
	Message   *string
	Phone     string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Status    string
}

type CreateRequestRow struct {
	ID              int32
	HouseID         int32
	UserID          int32
	GuestID         string
	Email           string
	Name            string
	Surname         string
	Lastname        string
	Count           int32
	Message         *string
	Phone           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ConfirmedAt     pgtype.Timestamp
	RejectionReason *string
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (CreateRequestRow, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.HouseID,
		arg.UserID,
		arg.GuestID,
		arg.Email,
		arg.Name,
		arg.Surname,
		arg.Lastname,
		arg.Count,
		arg.Message,
		arg.Phone,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var i CreateRequestRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.UserID,
		&i.GuestID,
		&i.Email,
		&i.Name,
		&i.Surname,
		&i.Lastname,
		&i.Count,
		&i.Message,
		&i.Phone,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
		&i.RejectionReason,
	)
	return i, err
}

const deleteExpiredPendingRequests = `-- name: DeleteExpiredPendingRequests :exec
DELETE FROM request
WHERE status = 'pending_verification'
  AND created_at < $1::timestamp
`

func (q *Queries) DeleteExpiredPendingRequests(ctx context.Context, before pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteExpiredPendingRequests, before)
	return err
}

const getHouseForBooking = `-- name: GetHouseForBooking :one
SELECT h.owner_id, h.status, u.email AS owner_email
FROM house h
JOIN "user" u ON h.owner_id = u.id
WHERE h.id = $1 AND h.deleted = false AND u.deleted = false
`

type GetHouseForBookingRow struct {
	OwnerID    int32
	Status     string
	OwnerEmail string
}

func (q *Queries) GetHouseForBooking(ctx context.Context, id int32) (GetHouseForBookingRow, error) {
	row := q.db.QueryRow(ctx, getHouseForBooking, id)
	var i GetHouseForBookingRow
	err := row.Scan(&i.OwnerID, &i.Status, &i.OwnerEmail)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT
  r.id, COALESCE(r.house_id, 0)::int AS house_id, COALESCE(r.user_id, 0)::int AS user_id,
  COALESCE(r.guest_id, '')::text AS guest_id, COALESCE(r.email, '')::text AS email,
  r.name, r.surname, r.lastname, r.count, r.message, r.phone,
  r.start_date, r.end_date, r.status, r.created_at, r.updated_at,
  r.confirmed_at, r.rejection_reason,
  h.street AS house_street, h.house_number AS house_number,
  COALESCE(h.number_room, '')::text AS house_number_room,
  h.country AS house_city, h.price AS house_price, h.owner_id AS house_owner_id,
  COALESCE((SELECT f.path FROM file f WHERE f.house_id = h.id AND f.deleted = false ORDER BY f.position LIMIT 1), '')::text AS house_cover_path,
  -- guest profile from user table
  COALESCE(u.name, '')::text       AS guest_name,
  COALESCE(u.surname, '')::text    AS guest_surname,
  COALESCE(u.patronymic, '')::text AS guest_patronymic,
  COALESCE(u.avatar_url, '')::text AS guest_avatar_url,
  COALESCE(u.phone, '')::text      AS guest_phone_profile,
  COALESCE(u.is_verified, false)   AS guest_is_verified,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    JOIN house hh ON hh.id = rv.house_id
    WHERE hh.owner_id = r.user_id AND rv.status = 'active'
  ), 0.0)::float8 AS guest_rating,
  (
    SELECT count(*)::int
    FROM review rv
    JOIN house hh ON hh.id = rv.house_id
    WHERE hh.owner_id = r.user_id AND rv.status = 'active'
  ) AS guest_reviews_count,
  -- owner profile from user table
  COALESCE(owner_u.name, '')::text       AS owner_name,
  COALESCE(owner_u.surname, '')::text    AS owner_surname,
  COALESCE(owner_u.patronymic, '')::text AS owner_patronymic,
  COALESCE(owner_u.avatar_url, '')::text AS owner_avatar_url,
  COALESCE(owner_u.phone, '')::text      AS owner_phone,
  COALESCE(owner_u.is_verified, false)   AS owner_is_verified,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    JOIN house hh ON hh.id = rv.house_id
    WHERE hh.owner_id = h.owner_id AND rv.status = 'active'
  ), 0.0)::float8 AS owner_rating,
  (
    SELECT count(*)::int
    FROM review rv
    JOIN house hh ON hh.id = rv.house_id
    WHERE hh.owner_id = h.owner_id AND rv.status = 'active'
  ) AS owner_reviews_count
FROM request r
JOIN house h ON h.id = r.house_id
LEFT JOIN "user" u ON u.id = r.user_id
LEFT JOIN "user" owner_u ON owner_u.id = h.owner_id
WHERE r.id = $1
`

type GetRequestByIDRow struct {
	ID                int32
	HouseID           int32
	UserID            int32
	GuestID           string
	Email             string
	Name              string
	Surname           string
	Lastname          string
	Count             int32
	Message           *string
	Phone             string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Status            string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	ConfirmedAt       pgtype.Timestamp
	RejectionReason   *string
	HouseStreet       string
	HouseNumber       string
	HouseNumberRoom   string
	HouseCity         string
	HousePrice        int32
	HouseOwnerID      int32
	HouseCoverPath    string
	GuestName         string
	GuestSurname      string
	GuestPatronymic   string
	GuestAvatarUrl    string
	GuestPhoneProfile string
	GuestIsVerified   bool
	GuestRating       float64
	GuestReviewsCount int32
	OwnerName         string
	OwnerSurname      string
	OwnerPatronymic   string
	OwnerAvatarUrl    string
	OwnerPhone        string
	OwnerIsVerified   bool
	OwnerRating       float64
	OwnerReviewsCount int32
}

func (q *Queries) GetRequestByID(ctx context.Context, id int32) (GetRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i GetRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.UserID,
		&i.GuestID,
		&i.Email,
		&i.Name,
		&i.Surname,
		&i.Lastname,
		&i.Count,
		&i.Message,
		&i.Phone,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
		&i.RejectionReason,
		&i.HouseStreet,
		&i.HouseNumber,
		&i.HouseNumberRoom,
		&i.HouseCity,
		&i.HousePrice,
		&i.HouseOwnerID,
		&i.HouseCoverPath,
		&i.GuestName,
		&i.GuestSurname,
		&i.GuestPatronymic,
		&i.GuestAvatarUrl,
		&i.GuestPhoneProfile,
		&i.GuestIsVerified,
		&i.GuestRating,
		&i.GuestReviewsCount,
		&i.OwnerName,
		&i.OwnerSurname,
		&i.OwnerPatronymic,
		&i.OwnerAvatarUrl,
		&i.OwnerPhone,
		&i.OwnerIsVerified,
		&i.OwnerRating,
		&i.OwnerReviewsCount,
	)
	return i, err
}

const houseHasConfirmedOverlap = `-- name: HouseHasConfirmedOverlap :one
SELECT EXISTS (
  SELECT 1
  FROM request rq
  WHERE rq.house_id = $1::int
    AND rq.status IN ('confirmed', 'active')
    AND rq.start_date < $2::date
    AND COALESCE(rq.end_date, rq.start_date + 1) > $3::date
) AS has_overlap
`

type HouseHasConfirmedOverlapParams struct {
	HouseID    int32
	RangeEnd   pgtype.Date
	RangeStart pgtype.Date
}

// Reports whether the house already has a confirmed or active request overlapping
// the requested [range_start, range_end) date range (half-open: end_date = checkout,
// free for next guest). The caller passes the exclusive end (start+1 for single night).
func (q *Queries) HouseHasConfirmedOverlap(ctx context.Context, arg HouseHasConfirmedOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, houseHasConfirmedOverlap, arg.HouseID, arg.RangeEnd, arg.RangeStart)
	var has_overlap bool
	err := row.Scan(&has_overlap)
	return has_overlap, err
}

const linkGuestRequests = `-- name: LinkGuestRequests :exec
DELETE FROM request
USING house
WHERE request.house_id = house.id
  AND LOWER(TRIM(request.email)) = LOWER(TRIM($1))
  AND request.user_id IS NULL
  AND request.status = 'pending_verification'
  AND house.owner_id = $2::int
`

type LinkGuestRequestsParams struct {
	Email  string
	UserID int32
}

func (q *Queries) LinkGuestRequests(ctx context.Context, arg LinkGuestRequestsParams) error {
	_, err := q.db.Exec(ctx, linkGuestRequests, arg.Email, arg.UserID)
	return err
}

const listBlockingRangesForHouse = `-- name: ListBlockingRangesForHouse :many
SELECT start_date, end_date, status
FROM request
WHERE house_id = $1
  AND status IN ('confirmed', 'active', 'in_progress', 'pending')
  AND (end_date IS NULL OR end_date >= CURRENT_DATE)
ORDER BY start_date
`

type ListBlockingRangesForHouseRow struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Status    string
}

// All active/pending date ranges for a house so the booking calendar can
// distinguish BLOCK ranges (confirmed, active) from WARN ranges (in_progress,
// pending). Interval is half-open [start_date, end_date): end_date = checkout
// day, free for same-day turnover. Past ranges are omitted.
func (q *Queries) ListBlockingRangesForHouse(ctx context.Context, houseID *int32) ([]ListBlockingRangesForHouseRow, error) {
	rows, err := q.db.Query(ctx, listBlockingRangesForHouse, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockingRangesForHouseRow
	for rows.Next() {
		var i ListBlockingRangesForHouseRow
		if err := rows.Scan(&i.StartDate, &i.EndDate, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByGuest = `-- name: ListRequestsByGuest :many
SELECT
  r.id, COALESCE(r.house_id, 0)::int AS house_id, COALESCE(r.user_id, 0)::int AS user_id,
  COALESCE(r.guest_id, '')::text AS guest_id, COALESCE(r.email, '')::text AS email,
  r.name, r.surname, r.lastname, r.count, r.message, r.phone,
  r.start_date, r.end_date, r.status, r.created_at, r.updated_at,
  r.confirmed_at, r.rejection_reason,
  h.street AS house_street, h.house_number AS house_number,
  COALESCE(h.number_room, '')::text AS house_number_room,
  h.country AS house_city, h.price AS house_price, h.owner_id AS house_owner_id,
  COALESCE((SELECT f.path FROM file f WHERE f.house_id = h.id AND f.deleted = false ORDER BY f.position LIMIT 1), '')::text AS house_cover_path
FROM request r
JOIN house h ON h.id = r.house_id
WHERE r.guest_id = $1::text
  AND (
    $2::text = 'all'
    OR ($2::text = 'active' AND (
      r.status = 'in_progress'
      OR r.status = 'pending_verification'
      OR (r.status = 'confirmed' AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE))
    ))
    OR ($2::text = 'history' AND (
      r.status = 'cancelled'
      OR (r.status = 'confirmed' AND r.end_date IS NOT NULL AND r.end_date < CURRENT_DATE)
    ))
  )
ORDER BY r.created_at DESC
LIMIT $4 OFFSET $3
`

type ListRequestsByGuestParams struct {
	GuestID      string
	Scope        string
	ResultOffset int32
	ResultLimit  int32
}

type ListRequestsByGuestRow struct {
	ID              int32
	HouseID         int32
	UserID          int32
	GuestID         string
	Email           string
	Name            string
	Surname         string
	Lastname        string
	Count           int32
	Message         *string
	Phone           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ConfirmedAt     pgtype.Timestamp
	RejectionReason *string
	HouseStreet     string
	HouseNumber     string
	HouseNumberRoom string
	HouseCity       string
	HousePrice      int32
	HouseOwnerID    int32
	HouseCoverPath  string
}

func (q *Queries) ListRequestsByGuest(ctx context.Context, arg ListRequestsByGuestParams) ([]ListRequestsByGuestRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByGuest,
		arg.GuestID,
		arg.Scope,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsByGuestRow
	for rows.Next() {
		var i ListRequestsByGuestRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.UserID,
			&i.GuestID,
			&i.Email,
			&i.Name,
			&i.Surname,
			&i.Lastname,
			&i.Count,
			&i.Message,
			&i.Phone,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfirmedAt,
			&i.RejectionReason,
			&i.HouseStreet,
			&i.HouseNumber,
			&i.HouseNumberRoom,
			&i.HouseCity,
			&i.HousePrice,
			&i.HouseOwnerID,
			&i.HouseCoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByUser = `-- name: ListRequestsByUser :many
SELECT
  r.id, COALESCE(r.house_id, 0)::int AS house_id, COALESCE(r.user_id, 0)::int AS user_id,
  COALESCE(r.guest_id, '')::text AS guest_id, COALESCE(r.email, '')::text AS email,
  r.name, r.surname, r.lastname, r.count, r.message, r.phone,
  r.start_date, r.end_date, r.status, r.created_at, r.updated_at,
  r.confirmed_at, r.rejection_reason,
  h.street AS house_street, h.house_number AS house_number,
  COALESCE(h.number_room, '')::text AS house_number_room,
  h.country AS house_city, h.price AS house_price, h.owner_id AS house_owner_id,
  COALESCE((SELECT f.path FROM file f WHERE f.house_id = h.id AND f.deleted = false ORDER BY f.position LIMIT 1), '')::text AS house_cover_path
FROM request r
JOIN house h ON h.id = r.house_id
WHERE r.user_id = $1::int
  AND (
    $2::text = 'all'
    OR ($2::text = 'active' AND (
      r.status = 'in_progress'
      OR (r.status = 'confirmed' AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE))
    ))
    OR ($2::text = 'history' AND (
      r.status = 'cancelled'
      OR (r.status = 'confirmed' AND r.end_date IS NOT NULL AND r.end_date < CURRENT_DATE)
    ))
  )
ORDER BY r.created_at DESC
LIMIT $4 OFFSET $3
`

type ListRequestsByUserParams struct {
	UserID       int32
	Scope        string
	ResultOffset int32
	ResultLimit  int32
}

type ListRequestsByUserRow struct {
	ID              int32
	HouseID         int32
	UserID          int32
	GuestID         string
	Email           string
	Name            string
	Surname         string
	Lastname        string
	Count           int32
	Message         *string
	Phone           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ConfirmedAt     pgtype.Timestamp
	RejectionReason *string
	HouseStreet     string
	HouseNumber     string
	HouseNumberRoom string
	HouseCity       string
	HousePrice      int32
	HouseOwnerID    int32
	HouseCoverPath  string
}

func (q *Queries) ListRequestsByUser(ctx context.Context, arg ListRequestsByUserParams) ([]ListRequestsByUserRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByUser,
		arg.UserID,
		arg.Scope,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsByUserRow
	for rows.Next() {
		var i ListRequestsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.UserID,
			&i.GuestID,
			&i.Email,
			&i.Name,
			&i.Surname,
			&i.Lastname,
			&i.Count,
			&i.Message,
			&i.Phone,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfirmedAt,
			&i.RejectionReason,
			&i.HouseStreet,
			&i.HouseNumber,
			&i.HouseNumberRoom,
			&i.HouseCity,
			&i.HousePrice,
			&i.HouseOwnerID,
			&i.HouseCoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForOwner = `-- name: ListRequestsForOwner :many
SELECT
  r.id, COALESCE(r.house_id, 0)::int AS house_id, COALESCE(r.user_id, 0)::int AS user_id,
  COALESCE(r.guest_id, '')::text AS guest_id, COALESCE(r.email, '')::text AS email,
  r.name, r.surname, r.lastname, r.count, r.message, r.phone,
  r.start_date, r.end_date, r.status, r.created_at, r.updated_at,
  r.confirmed_at, r.rejection_reason,
  h.street AS house_street, h.house_number AS house_number,
  COALESCE(h.number_room, '')::text AS house_number_room,
  h.country AS house_city, h.price AS house_price, h.owner_id AS house_owner_id,
  COALESCE((SELECT f.path FROM file f WHERE f.house_id = h.id AND f.deleted = false ORDER BY f.position LIMIT 1), '')::text AS house_cover_path,
  -- guest profile from user table
  COALESCE(u.name, '')::text       AS guest_name,
  COALESCE(u.surname, '')::text    AS guest_surname,
  COALESCE(u.patronymic, '')::text AS guest_patronymic,
  COALESCE(u.avatar_url, '')::text AS guest_avatar_url,
  COALESCE(u.phone, '')::text      AS guest_phone_profile,
  COALESCE(u.is_verified, false)   AS guest_is_verified,
  COALESCE((
    SELECT round(avg(rv.rating)::numeric, 1)
    FROM review rv
    JOIN house hh ON hh.id = rv.house_id
    WHERE hh.owner_id = r.user_id AND rv.status = 'active'
  ), 0.0)::float8 AS guest_rating,
  (
    SELECT count(*)::int
    FROM review rv
    JOIN house hh ON hh.id = rv.house_id
    WHERE hh.owner_id = r.user_id AND rv.status = 'active'
  ) AS guest_reviews_count
FROM request r
JOIN house h ON h.id = r.house_id
LEFT JOIN "user" u ON u.id = r.user_id
WHERE h.owner_id = $1
  AND r.status != 'pending_verification'
ORDER BY r.created_at DESC
LIMIT $3 OFFSET $2
`

type ListRequestsForOwnerParams struct {
	OwnerID      int32
	ResultOffset int32
	ResultLimit  int32
}

type ListRequestsForOwnerRow struct {
	ID                int32
	HouseID           int32
	UserID            int32
	GuestID           string
	Email             string
	Name              string
	Surname           string
	Lastname          string
	Count             int32
	Message           *string
	Phone             string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Status            string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	ConfirmedAt       pgtype.Timestamp
	RejectionReason   *string
	HouseStreet       string
	HouseNumber       string
	HouseNumberRoom   string
	HouseCity         string
	HousePrice        int32
	HouseOwnerID      int32
	HouseCoverPath    string
	GuestName         string
	GuestSurname      string
	GuestPatronymic   string
	GuestAvatarUrl    string
	GuestPhoneProfile string
	GuestIsVerified   bool
	GuestRating       float64
	GuestReviewsCount int32
}

func (q *Queries) ListRequestsForOwner(ctx context.Context, arg ListRequestsForOwnerParams) ([]ListRequestsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForOwner, arg.OwnerID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsForOwnerRow
	for rows.Next() {
		var i ListRequestsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.UserID,
			&i.GuestID,
			&i.Email,
			&i.Name,
			&i.Surname,
			&i.Lastname,
			&i.Count,
			&i.Message,
			&i.Phone,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfirmedAt,
			&i.RejectionReason,
			&i.HouseStreet,
			&i.HouseNumber,
			&i.HouseNumberRoom,
			&i.HouseCity,
			&i.HousePrice,
			&i.HouseOwnerID,
			&i.HouseCoverPath,
			&i.GuestName,
			&i.GuestSurname,
			&i.GuestPatronymic,
			&i.GuestAvatarUrl,
			&i.GuestPhoneProfile,
			&i.GuestIsVerified,
			&i.GuestRating,
			&i.GuestReviewsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRequest = `-- name: RejectRequest :one
UPDATE request
SET status = 'cancelled', rejection_reason = $1, updated_at = now()
WHERE id = $2 AND status = 'in_progress'
RETURNING
  id, COALESCE(house_id, 0)::int AS house_id, COALESCE(user_id, 0)::int AS user_id,
  COALESCE(guest_id, '')::text AS guest_id, COALESCE(email, '')::text AS email,
  name, surname, lastname, count, message, phone, start_date, end_date, status,
  created_at, updated_at, confirmed_at, rejection_reason
`

type RejectRequestParams struct {
	RejectionReason *string
	ID              int32
}

type RejectRequestRow struct {
	ID              int32
	HouseID         int32
	UserID          int32
	GuestID         string
	Email           string
	Name            string
	Surname         string
	Lastname        string
	Count           int32
	Message         *string
	Phone           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ConfirmedAt     pgtype.Timestamp
	RejectionReason *string
}

func (q *Queries) RejectRequest(ctx context.Context, arg RejectRequestParams) (RejectRequestRow, error) {
	row := q.db.QueryRow(ctx, rejectRequest, arg.RejectionReason, arg.ID)
	var i RejectRequestRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.UserID,
		&i.GuestID,
		&i.Email,
		&i.Name,
		&i.Surname,
		&i.Lastname,
		&i.Count,
		&i.Message,
		&i.Phone,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfirmedAt,
		&i.RejectionReason,
	)
	return i, err
}
