// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReviewsByAuthor = `-- name: CountReviewsByAuthor :one
SELECT count(*)
FROM review
WHERE owner_id = $1
`

func (q *Queries) CountReviewsByAuthor(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsByAuthor, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByHouse = `-- name: CountReviewsByHouse :one
SELECT count(*)
FROM review
WHERE house_id = $1::int
  AND status = 'active'
`

func (q *Queries) CountReviewsByHouse(ctx context.Context, houseID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsByHouse, houseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsForHost = `-- name: CountReviewsForHost :one
SELECT count(*)
FROM review rv
JOIN house h ON h.id = rv.house_id
WHERE h.owner_id = $1 AND rv.status = 'active'
`

func (q *Queries) CountReviewsForHost(ctx context.Context, ownerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsForHost, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO review (owner_id, house_id, body, rating, status, created_at)
VALUES ($1::int, $2::int, $3, $4::int, 'pending_moderation', now())
RETURNING id
`

type CreateReviewParams struct {
	OwnerID int32
	HouseID int32
	Body    string
	Rating  int32
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (int32, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.OwnerID,
		arg.HouseID,
		arg.Body,
		arg.Rating,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT
  rv.id,
  rv.house_id,
  rv.owner_id AS author_id,
  rv.rating,
  COALESCE(rv.original_body, rv.body)::text AS body,
  rv.status,
  COALESCE(rv.rejection_reason, '')::text AS rejection_reason,
  rv.request_id,
  rv.created_at,
  COALESCE(NULLIF(TRIM(concat_ws(' ', NULLIF(u.name, ''), NULLIF(u.patronymic, ''), NULLIF(u.surname, ''))), ''), 'Гость')::text AS author_name,
  COALESCE(u.avatar_url, '')::text AS author_avatar_url
FROM review rv
LEFT JOIN "user" u ON u.id = rv.owner_id
WHERE rv.id = $1::int
`

type GetReviewByIDRow struct {
	ID              int32
	HouseID         int32
	AuthorID        int32
	Rating          int32
	Body            string
	Status          string
	RejectionReason string
	RequestID       *int32
	CreatedAt       pgtype.Timestamp
	AuthorName      string
	AuthorAvatarUrl string
}

func (q *Queries) GetReviewByID(ctx context.Context, id int32) (GetReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i GetReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.AuthorID,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.RejectionReason,
		&i.RequestID,
		&i.CreatedAt,
		&i.AuthorName,
		&i.AuthorAvatarUrl,
	)
	return i, err
}

const listReviewsByAuthor = `-- name: ListReviewsByAuthor :many
SELECT
  rv.id,
  rv.house_id,
  rv.owner_id AS author_id,
  rv.rating,
  COALESCE(rv.original_body, rv.body)::text AS body,
  rv.status,
  COALESCE(rv.rejection_reason, '')::text AS rejection_reason,
  rv.request_id,
  rv.created_at,
  h.street AS house_street,
  h.house_number AS house_number,
  h.country AS house_city,
  COALESCE((SELECT f.path FROM file f WHERE f.house_id = h.id AND f.deleted = false ORDER BY f.position LIMIT 1), '')::text AS house_cover_path
FROM review rv
JOIN house h ON h.id = rv.house_id
WHERE rv.owner_id = $1
ORDER BY rv.created_at DESC, rv.id DESC
LIMIT $3 OFFSET $2
`

type ListReviewsByAuthorParams struct {
	OwnerID      int32
	ResultOffset int32
	ResultLimit  int32
}

type ListReviewsByAuthorRow struct {
	ID              int32
	HouseID         int32
	AuthorID        int32
	Rating          int32
	Body            string
	Status          string
	RejectionReason string
	RequestID       *int32
	CreatedAt       pgtype.Timestamp
	HouseStreet     string
	HouseNumber     string
	HouseCity       string
	HouseCoverPath  string
}

func (q *Queries) ListReviewsByAuthor(ctx context.Context, arg ListReviewsByAuthorParams) ([]ListReviewsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByAuthor, arg.OwnerID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByAuthorRow
	for rows.Next() {
		var i ListReviewsByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.AuthorID,
			&i.Rating,
			&i.Body,
			&i.Status,
			&i.RejectionReason,
			&i.RequestID,
			&i.CreatedAt,
			&i.HouseStreet,
			&i.HouseNumber,
			&i.HouseCity,
			&i.HouseCoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByHouse = `-- name: ListReviewsByHouse :many
SELECT
  rv.id,
  rv.house_id,
  rv.owner_id AS author_id,
  rv.rating,
  COALESCE(rv.published_body, rv.body)::text AS body,
  rv.created_at,
  COALESCE(NULLIF(TRIM(concat_ws(' ', NULLIF(u.name, ''), NULLIF(u.patronymic, ''), NULLIF(u.surname, ''))), ''), 'Гость')::text AS author_name,
  COALESCE(u.avatar_url, '')::text AS author_avatar_url
FROM review rv
LEFT JOIN "user" u ON u.id = rv.owner_id
WHERE rv.house_id = $1::int
  AND rv.status = 'active'
ORDER BY rv.created_at DESC, rv.id DESC
LIMIT $3 OFFSET $2
`

type ListReviewsByHouseParams struct {
	HouseID      int32
	ResultOffset int32
	ResultLimit  int32
}

type ListReviewsByHouseRow struct {
	ID              int32
	HouseID         int32
	AuthorID        int32
	Rating          int32
	Body            string
	CreatedAt       pgtype.Timestamp
	AuthorName      string
	AuthorAvatarUrl string
}

func (q *Queries) ListReviewsByHouse(ctx context.Context, arg ListReviewsByHouseParams) ([]ListReviewsByHouseRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByHouse, arg.HouseID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByHouseRow
	for rows.Next() {
		var i ListReviewsByHouseRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.AuthorID,
			&i.Rating,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForHost = `-- name: ListReviewsForHost :many
SELECT
  rv.id,
  rv.house_id,
  rv.owner_id AS author_id,
  rv.rating,
  COALESCE(rv.published_body, rv.body)::text AS body,
  rv.created_at,
  h.street AS house_street,
  h.house_number AS house_number,
  h.country AS house_city,
  COALESCE(NULLIF(TRIM(concat_ws(' ', NULLIF(u.name, ''), NULLIF(u.patronymic, ''), NULLIF(u.surname, ''))), ''), 'Гость')::text AS author_name,
  COALESCE(u.avatar_url, '')::text AS author_avatar_url,
  COALESCE((SELECT f.path FROM file f WHERE f.house_id = h.id AND f.deleted = false ORDER BY f.position LIMIT 1), '')::text AS house_cover_path
FROM review rv
JOIN house h ON h.id = rv.house_id
LEFT JOIN "user" u ON u.id = rv.owner_id
WHERE h.owner_id = $1 AND rv.status = 'active'
ORDER BY rv.created_at DESC, rv.id DESC
LIMIT $3 OFFSET $2
`

type ListReviewsForHostParams struct {
	OwnerID      int32
	ResultOffset int32
	ResultLimit  int32
}

type ListReviewsForHostRow struct {
	ID              int32
	HouseID         int32
	AuthorID        int32
	Rating          int32
	Body            string
	CreatedAt       pgtype.Timestamp
	HouseStreet     string
	HouseNumber     string
	HouseCity       string
	AuthorName      string
	AuthorAvatarUrl string
	HouseCoverPath  string
}

func (q *Queries) ListReviewsForHost(ctx context.Context, arg ListReviewsForHostParams) ([]ListReviewsForHostRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForHost, arg.OwnerID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsForHostRow
	for rows.Next() {
		var i ListReviewsForHostRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseID,
			&i.AuthorID,
			&i.Rating,
			&i.Body,
			&i.CreatedAt,
			&i.HouseStreet,
			&i.HouseNumber,
			&i.HouseCity,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.HouseCoverPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewSummaryByHouse = `-- name: ReviewSummaryByHouse :one
SELECT
  COALESCE(round(avg(rating)::numeric, 1), 0)::float8 AS average,
  (count(*))::int AS total,
  (count(*) FILTER (WHERE rating = 1))::int AS count1,
  (count(*) FILTER (WHERE rating = 2))::int AS count2,
  (count(*) FILTER (WHERE rating = 3))::int AS count3,
  (count(*) FILTER (WHERE rating = 4))::int AS count4,
  (count(*) FILTER (WHERE rating = 5))::int AS count5
FROM review
WHERE house_id = $1::int
  AND status = 'active'
`

type ReviewSummaryByHouseRow struct {
	Average float64
	Total   int32
	Count1  int32
	Count2  int32
	Count3  int32
	Count4  int32
	Count5  int32
}

func (q *Queries) ReviewSummaryByHouse(ctx context.Context, houseID int32) (ReviewSummaryByHouseRow, error) {
	row := q.db.QueryRow(ctx, reviewSummaryByHouse, houseID)
	var i ReviewSummaryByHouseRow
	err := row.Scan(
		&i.Average,
		&i.Total,
		&i.Count1,
		&i.Count2,
		&i.Count3,
		&i.Count4,
		&i.Count5,
	)
	return i, err
}

const reviewSummaryForHost = `-- name: ReviewSummaryForHost :one
SELECT
  COALESCE(round(avg(rv.rating)::numeric, 1), 0)::float8 AS average,
  (count(*))::int AS total,
  (count(*) FILTER (WHERE rv.rating = 1))::int AS count1,
  (count(*) FILTER (WHERE rv.rating = 2))::int AS count2,
  (count(*) FILTER (WHERE rv.rating = 3))::int AS count3,
  (count(*) FILTER (WHERE rv.rating = 4))::int AS count4,
  (count(*) FILTER (WHERE rv.rating = 5))::int AS count5
FROM review rv
JOIN house h ON h.id = rv.house_id
WHERE h.owner_id = $1::int
  AND rv.status = 'active'
`

type ReviewSummaryForHostRow struct {
	Average float64
	Total   int32
	Count1  int32
	Count2  int32
	Count3  int32
	Count4  int32
	Count5  int32
}

func (q *Queries) ReviewSummaryForHost(ctx context.Context, ownerID int32) (ReviewSummaryForHostRow, error) {
	row := q.db.QueryRow(ctx, reviewSummaryForHost, ownerID)
	var i ReviewSummaryForHostRow
	err := row.Scan(
		&i.Average,
		&i.Total,
		&i.Count1,
		&i.Count2,
		&i.Count3,
		&i.Count4,
		&i.Count5,
	)
	return i, err
}
